---
permalink: rhel-install/reference-backing-up-of-the-oncommand-workflow-automation-database.html 
sidebar: sidebar 
keywords: back up, oncommand, workflow, automation, database 
summary: 'WFA(OnCommand Workflow Automation) 데이터베이스 백업에는 시스템 구성 설정 및 운동장 데이터베이스를 비롯한 캐시 정보가 포함됩니다. 동일한 시스템이나 다른 시스템에서 복원을 위해 백업을 사용할 수 있습니다.' 
---
= OnCommand Workflow Automation 데이터베이스를 백업하는 중입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA(OnCommand Workflow Automation) 데이터베이스 백업에는 시스템 구성 설정 및 운동장 데이터베이스를 비롯한 캐시 정보가 포함됩니다. 동일한 시스템이나 다른 시스템에서 복원을 위해 백업을 사용할 수 있습니다.

데이터베이스의 자동 백업은 매일 오전 2시에 생성됩니다 WFA_INSTALL_LOCATION/WFA-BURNES에 .zip 파일로 저장됩니다.

WFA는 WFA 백업 디렉터리에 최대 5개의 백업을 저장하고 가장 오래된 백업을 최신 백업으로 대체합니다. WFA를 제거하면 WFA-Backups 디렉토리가 삭제되지 않습니다. WFA를 제거하는 동안 WFA 데이터베이스의 백업을 만들지 않은 경우 복원을 위해 자동으로 생성된 백업을 사용할 수 있습니다.

복원을 위해 특정 변경 사항을 저장해야 할 때 WFA 데이터베이스를 수동으로 백업할 수도 있습니다. 예를 들어 자동 백업을 수행하기 전에 변경한 내용을 백업하려면 다음과 같이 합니다.

[NOTE]
====
* WFA 데이터베이스 백업은 동일한 버전 또는 상위 버전의 WFA를 실행하는 시스템에만 복원할 수 있습니다.
+
예를 들어, WFA 4.2를 실행하는 시스템에서 백업을 생성한 경우, WFA 4.2 이상을 실행하는 시스템에만 백업을 복원할 수 있습니다.

* 고가용성 설정에서 재해 복구 중에 웹 UI를 사용하여 WFA 데이터베이스를 백업할 수 없습니다.


====


== 사용자 자격 증명 백업 및 복원

WFA 데이터베이스 백업에는 WFA 사용자 자격 증명이 포함되어 있습니다.


NOTE: WFA 데이터베이스는 AutoSupport 데이터에도 포함되어 있지만 WFA 사용자의 암호는 AutoSupport 데이터에 포함되지 않습니다.

백업에서 WFA 데이터베이스를 복원하면 다음 항목이 유지됩니다.

* 현재 WFA 설치 중에 생성한 admin 사용자 자격 증명입니다.
* 기본 admin 사용자 이외의 admin 권한이 있는 사용자가 데이터베이스를 복원하는 경우 두 admin 사용자의 자격 증명이 모두 복구됩니다.
* 현재 WFA 설치의 다른 모든 사용자 자격 증명이 백업의 사용자 자격 증명으로 교체됩니다.

