---
permalink: rhel-install/task-configure-vcs-to-install-wfa.html 
sidebar: sidebar 
keywords: configure, vcs, install, oncommand, workflow, automation 
summary: 'WFA(OnCommand Workflow Automation)를 VCS(Veritas Cluster Server)에 설치하기 전에 클러스터 노드가 WFA를 지원하도록 올바르게 구성되어 있는지 확인해야 합니다.' 
---
= OnCommand Workflow Automation를 설치하도록 VCS를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA(OnCommand Workflow Automation)를 VCS(Veritas Cluster Server)에 설치하기 전에 클러스터 노드가 WFA를 지원하도록 올바르게 구성되어 있는지 확인해야 합니다.

* VCS는 _Veritas Cluster Server 6.1.1 설치 가이드 _ 의 지침에 따라 클러스터의 두 노드에 모두 설치되어야 합니다.
* 클러스터 이벤트에 대한 알림을 받으려면 _Veritas Cluster Server Administrator's Guide _ 의 지침에 따라 SNMP 및 SMTP에 대해 VCS 소프트웨어를 구성해야 합니다.
* 클러스터 서버 구성에 대한 모든 요구사항과 지침은 VCS 설명서에 따라 충족되어야 합니다.
* UNIX용 SnapDrive를 사용하여 LUN을 생성하려면 UNIX용 SnapDrive를 설치해야 합니다.
* 두 클러스터 노드 모두 지원되는 버전의 운영 체제를 실행하고 있어야 합니다.
+
지원되는 최소 운영 체제는 Red Hat Enterprise Linux 7.0 및 VCS 6.1.1입니다.

* 두 클러스터 노드에서 동일한 경로를 사용하여 동일한 버전의 WFA를 설치해야 합니다.
* WFA 서버는 파이버 채널(FC) 또는 iSCSI를 통해 스토리지 시스템에 연결되어 있어야 합니다.
* 대기 시간은 WFA 서버와 스토리지 시스템 사이에 적어도 있어야 합니다.
* FC 링크는 활성 상태여야 하며, 생성된 LUN은 두 클러스터 노드에서 모두 액세스할 수 있어야 합니다.
* 각 시스템에 노드 간 통신을 위한 네트워크 인터페이스와 노드 간 통신을 위한 네트워크 인터페이스 등 최소 두 개의 네트워크 인터페이스를 설정해야 합니다.
* 노드-클라이언트 통신에 사용되는 네트워크 인터페이스의 이름은 두 시스템 모두에서 동일해야 합니다.
* 클러스터 노드 간에 별도의 하트비트 링크를 설정해야 합니다. 그렇지 않으면 네트워크 인터페이스를 사용하여 클러스터 노드 간에 통신합니다.
* 고가용성을 위해서는 공유 위치를 생성해야 합니다.
+
UNIX용 SnapDrive를 사용하여 공유 위치를 생성할 수 있습니다.

+
SnapDrive 또는 스토리지 시스템 명령줄 인터페이스를 사용하여 LUN을 관리할 수도 있습니다. 자세한 내용은 UNIX용 SnapDrive 호환성 매트릭스를 참조하십시오.



.단계
. VCS가 'hakstatus – summary'로 올바르게 설치되었는지 확인합니다
+
두 노드가 모두 온라인 상태여야 하며 두 노드에서 VCS 서비스가 실행되고 있어야 합니다.

. 다음 옵션 중 하나를 사용하여 두 노드에서 LUN을 액세스할 수 있는지 확인합니다.
+
** LUN을 기본적으로 관리합니다.
** UNIX용 SnapDrive 사용:
+
... 두 노드에 UNIX용 SnapDrive를 설치합니다.
... 두 노드에서 UNIX용 SnapDrive를 구성합니다.
... 첫 번째 노드에서 'SnapDrive storage create' 명령을 실행하여 LUN을 생성합니다.
... 'SnapDrive storage show –all' 명령을 실행하여 첫 번째 노드에서 생성된 LUN이 두 번째 노드에 표시되는지 확인합니다.





