---
permalink: rhel-install/task-configure-wfa-with-vcs-using-configuration-scripts-linux.html 
sidebar: sidebar 
keywords: configure, workflow, automation, vcs 
summary: 'VCS에 WFA(Workflow Automation)를 설치한 후에는 고가용성을 위해 구성 스크립트를 사용하여 VCS에서 WFA를 구성해야 합니다.' 
---
= VCS에서 워크플로우 자동화를 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
VCS에 WFA(Workflow Automation)를 설치한 후에는 고가용성을 위해 구성 스크립트를 사용하여 VCS에서 WFA를 구성해야 합니다.

* 두 클러스터 노드 모두에 동일한 버전의 WFA를 설치해야 합니다.
* 두 노드의 설치 경로가 동일해야 합니다.
* WFA 백업을 만들어야 합니다.


.단계
. 클러스터의 첫 번째 노드에 로그인합니다.
. Cluster Manager를 사용하여 두 노드의 HA 상태가 실행 중인지 확인합니다.
. 셸 프롬프트에서 ha_setup.pl 스크립트를 실행하여 WFA 데이터를 공유 위치로 이동하고 페일오버에 대해 VCS로 WFA를 구성합니다. ' perl ha_setup.pl -- first [-t type_of_cluster_vcs] [-g cluster_group_name] [-e NIC_card_name] [-i ip_address] [-m mask] [-n cluster_name] [-v mount lun_name] [-mount_name
+
기본 설치 위치의 경우, 스크립트는 /opt/netapp/WFA/bin/ha/에서 사용할 수 있습니다.

+
"perl ha_setup.pl --first-t vcs-g WFA-e eth0-i 10.238.170.3-m 255.255.255.0-n WFA_cluster -f /mnt/WFA_mount/-v lun_volume -d lun_dg -l/opt/netapp/WFA

. Cluster Manager를 사용하여 WFA 서비스, 마운트 지점, 가상 IP, NIC 및 볼륨 그룹이 클러스터 그룹에 추가되었는지 확인합니다.
. Cluster Manager를 사용하여 WFA 리소스를 2차 노드로 이동합니다.
+
.. 클러스터 그룹을 선택하고 마우스 오른쪽 버튼으로 클릭합니다.
.. Switch to * > * Secondary Node * 를 선택합니다.


. 데이터 마운트, 가상 IP, 볼륨 그룹 및 NIC 카드가 클러스터의 두 번째 노드에 있는지 확인합니다.
. Cluster Manager를 사용하여 WFA 서비스를 오프라인으로 전환합니다.
+
.. WFA * > * Application * > * WFA-server * 를 선택합니다.
.. 마우스 오른쪽 단추를 클릭하고 * 오프라인 * 을 선택합니다.
.. WFA * > * Application * > * WFA-dB * 를 선택합니다.
.. 마우스 오른쪽 단추를 클릭하고 * 오프라인 * 을 선택합니다.


. 쉘 프롬프트에서 클러스터의 보조 노드에 있는 ha_setup.pl 스크립트를 실행하여 공유 위치('perl ha_setup.pl -- join[-t type_of_cluster_vcs][-f mount_point_of_shared_lun]')의 데이터를 사용하도록 WFA를 구성합니다
+
기본 설치 위치의 경우, 스크립트는 /opt/netapp/WFA/bin/ha/에서 사용할 수 있습니다.

+
' perl ha_setup.pl - -join -t vcs -f /mnt/WFA_mount/'

. 클러스터 관리자로 이동하여 * 클러스터 그룹 * > * 온라인 * > * 서버 * 를 클릭합니다.
+
Cluster Manager에서 애플리케이션 리소스가 온라인 상태라고 표시하기까지는 시간이 걸릴 수 있습니다. 응용 프로그램 리소스를 마우스 오른쪽 단추로 클릭하고 리소스가 온라인 상태인지 확인할 수도 있습니다.

. 이 구성 중에 사용된 IP 주소를 통해 WFA에 액세스할 수 있는지 확인합니다.

