---
permalink: rhel-install/task-upgrade-mysql-on-linux.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, upgrade, mysql, linux 
summary: OnCommand Workflow Automation가 설치된 Linux 서버에서 최신 버전의 MySQL로 업그레이드하여 보안 취약점에 대한 수정 사항을 확인할 수 있습니다. 
---
= Linux에서 MySQL 업그레이드
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
OnCommand Workflow Automation가 설치된 Linux 서버에서 최신 버전의 MySQL로 업그레이드하여 보안 취약점에 대한 수정 사항을 확인할 수 있습니다.

WFA가 설치된 Linux 시스템에 대한 루트 권한이 있어야 합니다.


NOTE: WFA 4.2를 다시 설치하기 전에 MySQL을 제거한 경우 MySQL 데이터 디렉터리를 삭제해야 합니다.

MySQL 5.7의 업데이트(예: 5.7.22 ~ 5.7.26)로만 업그레이드할 수 있습니다. 예를 들어, MySQL 버전 5.8과 같은 주요 버전으로 업그레이드할 수 없습니다.

.단계
. WFA 호스트 시스템에서 루트 사용자로 로그인합니다.
. 대상 시스템에서 최신 MySQL Community Server.rpm 번들을 다운로드합니다.
. 번들을 대상 시스템의 디렉토리에 압축을 풉니다.
. 번들을 언타링 후 디렉토리에 여러 .rpm 패키지가 있지만 WFA는 다음 rpm 패키지만 필요합니다.
+
** mysql-community-client-5.7.x
** MySQL - 커뮤니티 - libs - 5.7.x
** mysql-community-server-5.7.x
** mysql-community-common-5.7.x
** MySQL - community-libs-compat-5.7.x 다른 .rpm 패키지를 모두 삭제합니다. RPM 번들에 모든 패키지를 설치하는데 문제가 발생하지는 않습니다.


. 셸 프롬프트에서 WFA 데이터베이스 및 서버 서비스를 중지합니다.
+
'service WFA-db stop

+
'service WFA-server stop

. 다음 명령을 사용하여 MySQL 업그레이드를 호출합니다.
+
rpm -Uvh *.rpm

+
'*.rpm'은 MySQL의 새 버전을 다운로드한 디렉터리에 있는 .rpm 패키지를 의미합니다.

. WFA 서비스를 시작합니다.
+
'service WFA-db start'를 선택합니다

+
'서비스 WFA - 서버 시작


