---
permalink: rhel-install/task-back-up-the-wfa-database-and-configurations-linux.html 
sidebar: sidebar 
keywords: back up, restore, oncommand, workflow, automation, database, configurations, linux 
summary: 'WFA(OnCommand Workflow Automation) 데이터베이스와 지원되는 구성을 백업 및 복원하면 재해 발생 시 데이터를 복구할 수 있습니다. 지원되는 구성에는 데이터 액세스, HTTP 시간 초과 및 SSL 인증서가 포함됩니다.' 
---
= Linux에서 OnCommand Workflow Automation 데이터베이스 및 구성을 백업 및 복구합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA(OnCommand Workflow Automation) 데이터베이스와 지원되는 구성을 백업 및 복원하면 재해 발생 시 데이터를 복구할 수 있습니다. 지원되는 구성에는 데이터 액세스, HTTP 시간 초과 및 SSL 인증서가 포함됩니다.

관리자 권한이나 설계자 자격 증명이 있어야 합니다.

백업을 복원하면 WFA에서 액세스하는 모든 스토리지 시스템에 액세스할 수 있으므로 안전한 위치에 백업을 생성해야 합니다.

[NOTE]
====
* 재해 복구 중에 WFA 데이터베이스 및 구성을 포괄적으로 백업해야 하며 독립 실행형 환경과 고가용성 환경 모두에서 사용할 수 있습니다.
* 재해 복구 중에 포괄적인 백업 및 복원 작업을 위해 CLI 명령 또는 REST API만 사용할 수 있습니다.
+
재해 복구 중에 WFA 데이터베이스를 백업 또는 복원하는 데 웹 UI를 사용할 수 없습니다.



====
.단계
. OnCommand Workflow Automation 데이터베이스를 백업합니다.
+
link:reference-backing-up-of-the-oncommand-workflow-automation-database.html["OnCommand Workflow Automation 데이터베이스를 백업하는 중입니다"]

. OnCommand Workflow Automation 데이터베이스의 이전 백업을 복원합니다.
+
link:concept-restoring-the-wfa-database.html["OnCommand Workflow Automation 데이터베이스를 복원하는 중입니다"]


