---
permalink: windows-install/reference-system-requirements-for-oncommand-workflow-automation-windows.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, system requirements, install 
summary: 'WFA를 설치하기 전에 WFA(OnCommand Workflow Automation) 하드웨어 및 소프트웨어 요구 사항을 숙지해야 합니다.' 
---
= OnCommand Workflow Automation 설치를 위한 시스템 요구 사항
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA를 설치하기 전에 WFA(OnCommand Workflow Automation) 하드웨어 및 소프트웨어 요구 사항을 숙지해야 합니다.



== WFA 설치를 위한 하드웨어 요구사항

다음 표에는 WFA 서버의 최소 하드웨어 요구사항 및 권장 하드웨어 사양이 나와 있습니다.

[cols="3*"]
|===
| 구성 요소 | 최소 요구 사항 | 권장 사양 


 a| 
CPU
 a| 
2.27GHz 이상, 4코어, 64비트
 a| 
2.27GHz 이상, 4코어, 64비트



 a| 
RAM
 a| 
4GB
 a| 
8GB



 a| 
사용 가능한 디스크 공간
 a| 
5GB
 a| 
20GB

|===
가상 머신(VM)에 WFA를 설치하는 경우 필요한 메모리와 CPU를 예약하여 VM에 충분한 리소스가 있어야 합니다. 설치 프로그램이 CPU 속도를 확인하지 않습니다.



== WFA 설치를 위한 소프트웨어 요구사항

WFA는 64비트 Windows 운영 체제에서 실행되며, 전용 물리적 시스템 또는 VM에 설치해야 합니다. WFA를 실행하는 서버에 다른 애플리케이션을 설치해서는 안 됩니다.

WFA는 Microsoft Windows Server 2012 Enterprise Edition에서 Microsoft Windows Server 2016(모든 에디션)까지 실행됩니다. Enterprise Edition이 권장되는 Windows 운영 체제입니다.

Windows 2012 서버의 경우 Windows 시스템에 .NET Framework 버전 4.5.2가 설치되어 있어야 합니다. NET Framework 버전 4.5.2가 설치되어 있지 않으면 WFA 5.1을 설치하지 못합니다.

* 다음 브라우저 중 하나:
+
** Mozilla Firefox
** Microsoft Internet Explorer를 참조하십시오
** Google Chrome


* PowerShell 3.0
* VMware PowerCLI 버전 5
+

NOTE: VMware API를 위한 PowerShell 확장은 WFA를 사용하여 VMware vSphere에서 워크플로우를 실행하는 경우에만 필요합니다.




NOTE: 바이러스 백신 애플리케이션이 WFA 서비스를 시작하지 못할 수 있습니다.

이 문제를 방지하려면 다음 WFA 디렉토리에 대한 바이러스 검사 제외를 구성합니다.

* WFA가 설치된 디렉토리입니다
* Perl을 설치한 디렉토리입니다
* OpenJDK를 설치한 디렉토리입니다
* MySQL 데이터 디렉토리


자세한 내용은 상호 운용성 매트릭스 툴을 참조하십시오.

* 관련 정보 *

https://mysupport.netapp.com/matrix["NetApp 상호 운용성 매트릭스 툴"^]
