---
permalink: windows-install/task-create-a-certificate-signing-request-for-workflow-automation-windows.html 
sidebar: sidebar 
keywords: workflow, automation, wfa, windows, create, certificate, sign, request 
summary: 'Windows에서 인증서 서명 요청(CSR)을 생성하여 WFA(Workflow Automation)용 기본 SSL 인증서 대신 CA(인증 기관)에서 서명한 SSL 인증서를 사용할 수 있습니다.' 
---
= Workflow Automation에 대한 인증서 서명 요청을 생성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Windows에서 인증서 서명 요청(CSR)을 생성하여 WFA(Workflow Automation)용 기본 SSL 인증서 대신 CA(인증 기관)에서 서명한 SSL 인증서를 사용할 수 있습니다.

* WFA 서버에 Windows 관리자 권한이 있어야 합니다.
* WFA에서 제공하는 기본 SSL 인증서를 교체해야 합니다.


기본 WFA 설치 경로가 이 절차에 사용됩니다. 설치 중에 기본 경로를 변경한 경우 사용자 지정 WFA 설치 경로를 사용해야 합니다.

.단계
. WFA 호스트 시스템에서 admin 사용자로 로그인합니다.
. WFA 서버에서 명령 프롬프트를 열고 디렉터리를 + <OpenJDK_install_location>\bin 위치로 변경합니다
. CSR 생성:
+
"keytool-certreq-keystore WFA_install_location\WFA\jboss\standalone\configuration\keystore\WFA.keystore-alias "SSL keystore" -file C:\file_name.csr"

+
file_name 은 CSR 파일의 이름입니다.

. 메시지가 표시되면 암호를 입력합니다(기본값 또는 새 암호).
+
기본 암호는 임의로 생성된 암호화된 암호입니다.

+
기본 암호를 받아서 해독하려면 기술 자료 문서의 단계를 사용합니다 link:https://kb.netapp.com/?title=Advice_and_Troubleshooting%2FData_Infrastructure_Management%2FOnCommand_Suite%2FHow_to_renew_the_self-signed_certificate_on_WFA_5.1.1.0.4%253F["WFA 5.1.1.0.4에서 자체 서명된 인증서를 갱신하는 방법"^]

. CA에 file_name.csr 파일을 보내 서명된 인증서를 얻습니다.
+
자세한 내용은 CA 웹 사이트를 참조하십시오.

. CA에서 체인 인증서를 다운로드한 다음 키 저장소로 체인 인증서를 가져옵니다. ' keytool -import -alias " SSL keystore CA certificate " -keystore "WFA_install_location\WFA\jboss\standalone\configuration\keystore\WFA.keystore" -trustcacerts -file C:\chain_cer"
+
C:\chain_cert.cer는 CA로부터 받은 체인 인증서 파일입니다. 파일은 X.509 형식이어야 합니다.

. CA로부터 받은 서명된 인증서를 가져옵니다.
+
'keytool-import-alias "SSL keystore" -keystore "WFA_install_location\WFA\jboss\standalone\configuration\keystore\WFA.keystore" -file C:\certificate.cer"

+
C:\certificate.cer는 CA로부터 받은 체인 인증서 파일입니다.

. 다음 WFA 서비스를 시작합니다.
+
** NetApp WFA 데이터베이스
** NetApp WFA 서버



