---
permalink: windows-install/task-configure-authentication-settings.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, configure, authentication settings 
summary: '인증 및 승인을 위해 Microsoft Active Directory(AD) LDAP(Lightweight Directory Access Protocol) 서버를 사용하도록 WFA(OnCommand Workflow Automation)를 구성할 수 있습니다.' 
---
= 인증 설정을 구성합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
인증 및 승인을 위해 Microsoft Active Directory(AD) LDAP(Lightweight Directory Access Protocol) 서버를 사용하도록 WFA(OnCommand Workflow Automation)를 구성할 수 있습니다.

사용자 환경에서 Microsoft AD LDAP 서버를 구성해야 합니다.

WFA에는 Microsoft AD LDAP 인증만 지원됩니다. Microsoft AD LDS(Lightweight Directory Services) 또는 Microsoft Global Catalog를 비롯한 다른 LDAP 인증 방법은 사용할 수 없습니다.


NOTE: 통신 중에 LDAP는 사용자 이름과 암호를 일반 텍스트로 보냅니다. 그러나 LDAPS(LDAP 보안) 통신은 암호화되어 안전하게 보호됩니다.

.단계
. 웹 브라우저를 통해 admin으로 WFA에 로그인합니다.
. 설정 * 을 클릭하고 * 설정 * 에서 * 인증 * 을 클릭합니다.
. Active Directory* 활성화 확인란을 선택합니다.
. 필드에 필수 정보를 입력합니다.
+
.. 도메인 사용자에 대해 user@domain 형식을 사용하려면 sAMAccountName을 * 사용자 이름 특성 * 필드의 userPrincipalName으로 바꿉니다.
.. 환경에 고유한 값이 필요한 경우 필수 필드를 편집합니다.
.. AD 서버 URI를 'LDAP://active_directory_server_address\[:port\]'와 같이 입력한다
+
LDAP://NB-T01.example.com[:389]

+
SSL을 통해 LDAP를 활성화한 경우 'LDAPS://active_directory_server_address\[:port\]'라는 URI 형식을 사용할 수 있습니다

.. 필요한 역할에 필요한 AD 그룹 이름 목록을 추가합니다.
+

NOTE: Active Directory 그룹 창에서 필요한 역할에 AD 그룹 이름 목록을 추가할 수 있습니다.



. 저장 * 을 클릭합니다.
. 어레이에 대한 LDAP 연결이 필요한 경우 WFA 서비스를 필요한 도메인 사용자로 로그온하도록 구성합니다.
+
.. services.msc를 사용하여 Windows 서비스 콘솔을 엽니다.
.. NetApp WFA Server * 서비스를 두 번 클릭합니다.
.. NetApp WFA Server 속성 대화 상자에서 * 로그온 * 탭을 클릭한 다음 * 이 계정 * 을 선택합니다.
.. 도메인 사용자 이름과 암호를 입력한 다음 * 확인 * 을 클릭합니다.



