---
permalink: windows-install/task-manage-site-specific-perl-modules.html 
sidebar: sidebar 
keywords: manage, site-specific, perl modules 
summary: 'ActiveState Perl Package Manager(PPM)를 사용하여 사이트별 Perl 모듈을 관리할 수 있습니다. WFA를 업그레이드하는 동안 Perl 모듈이 삭제되지 않도록 WFA(OnCommand Workflow Automation) 설치 디렉토리 외부에 사이트별 Perl 모듈을 설치해야 합니다.' 
---
= 사이트별 Perl 모듈을 관리합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
ActiveState Perl Package Manager(PPM)를 사용하여 사이트별 Perl 모듈을 관리할 수 있습니다. WFA를 업그레이드하는 동안 Perl 모듈이 삭제되지 않도록 WFA(OnCommand Workflow Automation) 설치 디렉토리 외부에 사이트별 Perl 모듈을 설치해야 합니다.

PERL5LIB 환경 변수를 사용하면 WFA 서버에 설치된 Perl 해석기를 구성하여 Perl 모듈을 사용할 수 있습니다.

이 절차의 예로 c:\Perl의 사용자 영역에 try-Tiny Perl 모듈을 설치하는 것이 있습니다. WFA를 제거해도 이 사용자 영역이 삭제되지 않으며 WFA를 다시 설치하거나 업그레이드한 후에 이 영역을 다시 사용할 수 있습니다.

.단계
. PERL5LIB 환경 변수를 Perl 모듈을 설치할 위치로 설정합니다.
+
''c:\>%PERL5LIB%''c:\Perl'

. Perl module 영역이 ppm Area List를 사용하여 초기화 되지 않았는지 확인한다.
+
'c:\Program Files\NetApp\WFA\Perl64\bin> ppm 영역 목록'

+
[listing]
----
┌────────┬──────┬───────────────────────────────────────────────────┐
│ name   │ pkgs │ lib                                               │
├────────┼──────┼───────────────────────────────────────────────────┤
│ (user) │  n/a │ C:/Perl                                           │
│  site* │  0   │ C:/Program Files/NetApp/WFA/Perl64/site/lib       │
│  perl  │  229 │ C:/Program Files/NetAPP/WFA/Perl64/lib            │
└────────┴──────┴───────────────────────────────────────────────────┘
----
. ppm area init user를 이용하여 Perl 모듈 영역을 초기화 한다.
+
'c:\Program Files\NetApp\WFA\Perl64\bin> ppm 영역 초기화 사용자'

+
[listing]
----
Syncing user PPM database with .packlists...done
----
. Perl Module 영역이 ppm Area List를 사용하여 초기화되었는지 확인한다.
+
'c:\Program Files\NetApp\WFA\Perl64\bin> ppm 영역 목록'

+
[listing]
----
┌────────┬──────┬───────────────────────────────────────────────────┐
│ name   │ pkgs │ lib                                               │
├────────┼──────┼───────────────────────────────────────────────────┤
│  user  │  0   │ C:/Perl                                           │
│  site* │  0   │ C:/Program Files/NetApp/WFA/Perl64/site/lib       │
│  perl  │  229 │ C:/Program Files/NetAPP/WFA/Perl64/lib            │
└────────┴──────┴───────────────────────────────────────────────────┘
----
. 필요한 리포지토리를 추가하고 필요한 패키지를 설치합니다.
+
.. ppm repo add를 사용하여 필요한 리포지토리를 추가합니다.
+
'+c:\Program Files\NetApp\WFA\Perl64\bin> ppm repo add http://ppm4.activestate.com/MSWin32-x64/5.16/1600/package.xml+`[]

+
[listing]
----
Downloading ppm4.activestate.com packlist...done
Updating ppm4.activestate.com database...done
Repo 1 added.
----
.. ppm repo list를 사용하여 필요한 리포지터리가 추가되었는지 확인한다.
+
'c:\Program Files\NetApp\WFA\Perl64\bin > ppm repo list'

+
[listing]
----
┌────────┬──────┬────────────────────────────────────────────────┐
│ id     │ pkgs │ name                                           │
├────────┼──────┼────────────────────────────────────────────────┤
│  1     │17180 │ ppmr.activestate.com                           │
└────────┴──────┴────────────────────────────────────────────────┘
 (1 enabled repository)
----
.. ppm install을 사용하여 필요한 Perl 모듈을 설치합니다.
+
'c:\Program Files\NetApp\WFA\Perl64\bin> ppm 설치 시험 사용 영역 사용자

+
[listing]
----
Downloading ppm4.activestate.com packlist...done
Updating ppm4.activestate.com database...done
Downloading Try-Tiny-0.18...done
Unpacking Try-Tiny-0.18...done
Generating HTML for Try-Tiny-0.18...done
Updating files in user area...done
   2 files installed
----
.. ppm Area List를 사용하여 필요한 Perl 모듈이 설치되어 있는지 확인한다.
+
'c:\Program Files\NetApp\WFA\Perl64\bin> ppm 영역 목록'

+
[listing]
----
┌────────┬──────┬────────────────────────────────────────────────┐
│ name   │ pkgs │ lib                                            │
├────────┼──────┼────────────────────────────────────────────────┤
│  user  │  1   │ C:/Perl                                        │
│  site* │  0   │ C:/Program Files/NetApp/WFA/Perl64/site/lib    │
│  perl  │  229 │ C:/Program Files/NetAPP/WFA/Perl64/lib         │
└────────┴──────┴────────────────────────────────────────────────┘
----



