---
permalink: help/concept-how-you-define-user-input.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, wfa, user, input, data, options, available, execution, define, parameters, enhance, flexibility, usability 
summary: 'WFA(OnCommand Workflow Automation) 사용자 입력은 워크플로우를 실행하는 동안 사용할 수 있는 데이터 입력 옵션입니다. 워크플로우의 유연성과 사용 편의성을 개선하려면 사용자 입력 매개 변수를 정의해야 합니다.' 
---
= 사용자 입력 정의 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA(OnCommand Workflow Automation) 사용자 입력은 워크플로우를 실행하는 동안 사용할 수 있는 데이터 입력 옵션입니다. 워크플로우의 유연성과 사용 편의성을 개선하려면 사용자 입력 매개 변수를 정의해야 합니다.

사용자 입력은 입력 필드로 표시되며 워크플로를 미리 보거나 실행할 때 관련 데이터로 채울 수 있습니다. 달러 기호($)로 레이블 또는 변수를 미리 고정하여 워크플로에서 명령 세부 정보를 지정할 때 사용자 입력 필드를 만들 수 있습니다. 예를 들어, '$VolumeName'은 'Volume Name' 사용자 입력 필드를 생성합니다. WFA는 Workflow <Workflow name> 창의 User Inputs 탭에 사용자가 만든 사용자 입력 레이블을 자동으로 채웁니다. 또한 유형, 표시 이름, 기본값 및 유효성 검사 값과 같은 사용자 입력 특성을 수정하여 사용자 입력 유형을 정의하고 입력 필드를 사용자 지정할 수도 있습니다.



== 사용자 입력 유형 옵션

* * 문자열 *
+
유효한 값(예: *)에 정규식을 사용할 수 있습니다.

+
0d 0f 0f 등의 문자열은 double형 0으로 평가되는 0d와 비슷한 숫자로 평가된다.

* * 번호 *
+
선택할 수 있는 숫자 범위(예: 1 ~ 15)를 정의할 수 있습니다.

* * Enum *
+
enum 형식을 사용하여 사용자 입력 필드를 채울 때 선택할 수 있는 열거형 값을 만들 수 있습니다. 사용자가 만든 enum 값을 선택적으로 잠가 사용자 입력에 대해 만든 값만 선택하도록 할 수 있습니다.

* * 쿼리 *
+
WFA 캐시에 있는 값에서 사용자 입력을 선택하려면 쿼리 유형을 선택할 수 있습니다. 예를 들어, 다음 쿼리를 사용하여 WFA 캐시의 IP 주소 및 이름 값, 즉 'Select IP, name from storage.array'로 사용자 입력 필드를 자동으로 채울 수 있습니다 쿼리에 의해 다시 시도된 결과만 선택하도록 쿼리에서 검색한 값을 잠글 수도 있습니다.

* * 쿼리(다중 선택) *
+
쿼리 유형과 유사한 쿼리(다중 선택) 형식을 사용하면 워크플로를 실행하는 동안 여러 값을 선택할 수 있습니다. 예를 들어, 사용자는 공유 및 내보내기와 함께 여러 볼륨 또는 볼륨을 선택할 수 있습니다. 사용자가 여러 행을 선택할 수 있도록 하거나 선택 영역을 단일 행으로 제한할 수 있습니다. 행을 선택하면 선택한 행의 모든 열에서 값이 선택됩니다.

+
사용자 입력의 쿼리(다중 선택) 유형을 사용할 때 다음 함수를 사용할 수 있습니다.

+
** getSize
** getValueAt
** getValueAt2D
** getValueFrom2DByRowKey


* * 부울 *
+
부울 형식을 사용하여 사용자 입력 대화 상자에 확인란을 표시할 수 있습니다. 가능한 값으로 ""true" 및 ""false""를 가진 사용자 입력에 부울 형식을 사용해야 합니다.

* * 표 *
+
사용자 입력의 테이블 형식을 사용하여 워크플로를 실행하는 동안 여러 값을 입력하는 데 사용할 수 있는 테이블의 열 머리글을 지정할 수 있습니다. 예를 들어, 노드 이름 및 포트 이름의 목록을 지정하는 데 사용할 수 있는 테이블입니다. 또한 다음 사용자 입력 형식 중 하나를 열 머리글에 지정하여 런타임 중에 입력한 값의 유효성을 검사할 수도 있습니다.

+
** 문자열
** 번호
** 번호
** 부울
** 쿼리




string 은 열 머리글의 기본 사용자 입력 유형입니다. 다른 사용자 입력 유형을 지정하려면 유형 열을 두 번 클릭해야 합니다.

디자이너에서 SnapMirror 정책 및 규칙 만들기 워크플로를 열어 사용자 입력 형식이 "'PolicyRule'" 사용자 입력에 어떻게 사용되는지 확인할 수 있습니다.

사용자 입력의 테이블 유형을 사용할 때 다음 기능을 사용할 수 있습니다.

* getSize
* getValueAt
* getValueAt2D
* getValueFrom2DByRowKey


Designer에서 * 무한 확장 볼륨 * 을 사용하여 스토리지 가상 머신 생성 및 구성 워크플로우를 열어 테이블 유형 사용 방법을 확인할 수 있습니다.

* * 암호 *
+
암호 입력을 위한 사용자 입력에 암호 유형을 사용할 수 있습니다. 사용자가 입력한 암호는 암호화되어 WFA 애플리케이션 및 로그 파일에 별표 문자 시퀀스로 표시됩니다. 다음 기능을 사용하여 암호를 해독한 다음 명령을 통해 사용할 수 있습니다.

+
** Perl 명령의 경우: WFAUtil::getWfaInputPassword($password)
** PowerShell 명령의 경우 Get-WfaInputPassword - EncryptedPassword$ password 를 사용합니다
+
여기서 $password는 WFA를 통해 명령으로 전달되는 암호화된 암호입니다.



* * 사전 *
+
선택한 사전 항목에 대한 테이블 데이터를 추가할 수 있습니다. 사전 항목 속성은 반환할 속성을 선택합니다. 워크플로를 실행하는 동안 단일 값 또는 여러 값을 선택할 수 있습니다. 예를 들어, 단일 볼륨 또는 여러 볼륨을 선택할 수 있습니다. 기본적으로 단일 값이 선택됩니다. 필터링할 규칙을 선택할 수도 있습니다. 규칙은 사전 항목 속성, 연산자 및 값으로 구성됩니다. 이 특성에는 해당 참조의 속성도 포함될 수 있습니다.

+
예를 들어, 이름이 ""aggr""이고 사용 가능한 크기가 5GB보다 큰 모든 애그리게이트를 나열하여 집계에 대한 규칙을 지정할 수 있습니다. 그룹의 첫 번째 규칙은 이름, 연산자 'tarts-with', 값 aggr입니다. 같은 그룹에 대한 두 번째 규칙은 연산자 > 와 값 5000을 가진 속성 Available_size_MB 입니다.



다음 표에는 사용자 입력 유형에 적용할 수 있는 옵션이 나와 있습니다.

[cols="2*"]
|===
| 옵션을 선택합니다 | 설명 


 a| 
검증 중
 a| 
사용자가 유효한 값만 입력하도록 사용자 입력 유형을 검증할 수 있습니다.

* 사용자 입력의 문자열 및 숫자 유형은 워크플로의 실행 시간 동안 입력한 값으로 유효성을 검사할 수 있습니다.
* 문자열 형식은 정규식을 사용하여 유효성을 검사할 수도 있습니다.
* 숫자 형식은 숫자 부동 소수점 필드이며 지정된 숫자 범위를 사용하여 유효성을 검사할 수 있습니다.




 a| 
잠금 값
 a| 
사용자가 드롭다운 값을 덮어쓰지 않고 표시된 값만 선택할 수 있도록 쿼리 및 enum 형식의 값을 잠글 수 있습니다.



 a| 
필수로 표시
 a| 
사용자가 특정 사용자 입력을 입력해야 워크플로를 계속 실행할 수 있도록 사용자 입력을 필수로 표시할 수 있습니다.



 a| 
그룹화
 a| 
관련 사용자 입력을 그룹화하고 사용자 입력 그룹의 이름을 제공할 수 있습니다. 사용자 입력 대화 상자에서 그룹을 확장하고 축소할 수 있습니다. 기본적으로 확장해야 하는 그룹을 선택할 수 있습니다.



 a| 
조건 적용
 a| 
조건부 사용자 입력 기능을 사용하면 다른 사용자 입력에 대해 입력된 값을 기반으로 사용자 입력 값을 설정할 수 있습니다. 예를 들어 NAS 프로토콜을 구성하는 워크플로우에서 프로토콜에 필요한 사용자 입력을 NFS로 지정하여 ""읽기/쓰기 호스트 목록"" 사용자 입력을 활성화할 수 있습니다.

|===