---
permalink: help/concept-what-return-parameters-are.html 
sidebar: sidebar 
keywords: return, parameter, available, planning, phase, workflow, values, return, debugging, understand 
summary: 반환 매개 변수는 워크플로의 계획 단계 이후에 사용할 수 있는 매개 변수입니다. 이러한 매개 변수에서 반환하는 값은 워크플로를 디버깅하는 데 유용합니다. 반환 매개 변수의 작동 방식과 워크플로를 디버깅하기 위한 반환 매개 변수로 사용할 수 있는 매개 변수를 이해해야 합니다. 
---
= 반환 매개 변수의 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
반환 매개 변수는 워크플로의 계획 단계 이후에 사용할 수 있는 매개 변수입니다. 이러한 매개 변수에서 반환하는 값은 워크플로를 디버깅하는 데 유용합니다. 반환 매개 변수의 작동 방식과 워크플로를 디버깅하기 위한 반환 매개 변수로 사용할 수 있는 매개 변수를 이해해야 합니다.

워크플로에서 변수 특성, 식 및 사용자 입력 값과 같은 매개 변수 집합을 반환 매개 변수로 지정할 수 있습니다. 워크플로 실행 중에 지정된 매개 변수의 값이 계획 단계에 채워지고 워크플로 실행이 시작됩니다. 그런 다음 이러한 매개 변수의 값이 워크플로의 특정 실행에서 계산된 방식으로 반환됩니다. 워크플로를 디버깅하려면 매개 변수에서 반환한 값을 참조할 수 있습니다.

이러한 매개 변수에 대해 계산되거나 선택된 값을 확인하려는 경우 워크플로에서 필수 반환 매개 변수를 지정할 수 있습니다. 예를 들어 자원 선택 논리를 사용하여 워크플로에서 집계를 선택할 때 워크플로 계획 중에 선택한 집계를 볼 수 있도록 반환 매개 변수로 "집계"를 지정할 수 있습니다.

워크플로를 디버깅하기 위한 반환 매개 변수 값을 참조하기 전에 워크플로 실행이 완료되었는지 확인해야 합니다. 반환 매개 변수 값은 각 워크플로 실행에 대해 설정됩니다. 워크플로의 여러 실행 후에 반환 매개 변수를 추가한 경우에는 매개 변수를 추가한 후에만 해당 매개 변수의 값을 실행할 수 있습니다.



== 반환 매개 변수로 사용할 수 있는 매개 변수입니다

[cols="2*"]
|===
| 매개 변수를 반환합니다 | 예 


 a| 
스칼라 변수 특성입니다
 a| 
''볼륨 이름'' 변수의 속성인 volume1.name,`



 a| 
상수
 a| 
최대_볼륨_크기



 a| 
사용자 입력
 a| 
$클러스터 이름



 a| 
변수 특성, 상수 및 사용자 입력을 포함하는 MVEL 식입니다
 a| 
volume1.name+'-'+$clusterName



 a| 
실행 중에 명령이 추가하는 반환 매개 변수입니다
 a| 
PowerShell 명령에서 'Add-WfaWorkflowParameter-Name 'VolumeUUID'-Value''12345'-AddAsReturnParameter$ true' 줄을 사용하면 '$volumeUUID' 매개 변수가 반환 매개 변수로 추가됩니다

|===


== 사전 정의된 워크플로의 반환 매개 변수 예

반환 매개 변수의 지정 방법을 이해하려면 Designer에서 다음 미리 정의된 워크플로를 열고 지정된 반환 매개 변수를 검토할 수 있습니다.

* vFiler에서 NFS 볼륨을 생성합니다
* vFiler에서 Qtree CIFS 공유를 생성합니다
* Clustered Data ONTAP 볼륨 CIFS 공유를 생성합니다

