---
permalink: help/concept-how-you-define-workflows.html 
sidebar: sidebar 
keywords: goal, workflow, steps, execute, arrange, complete, workflow 
summary: 워크플로의 목표를 워크플로에서 실행해야 하는 단계로 나누어야 합니다. 그런 다음 워크플로를 완료하기 위한 단계를 정렬할 수 있습니다. 
---
= 워크플로우를 정의하는 방법
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
워크플로의 목표를 워크플로에서 실행해야 하는 단계로 나누어야 합니다. 그런 다음 워크플로를 완료하기 위한 단계를 정렬할 수 있습니다.

워크플로는 종단 간 프로세스를 완료하는 데 필요한 일련의 단계를 포함하는 알고리즘입니다. 프로세스의 범위는 워크플로의 목표에 따라 달라질 수 있습니다. 워크플로우 목표는 스토리지 운영만 처리하거나 네트워킹, 가상화, IT 시스템 및 기타 애플리케이션을 단일 프로세스로 처리하는 등 보다 복잡한 프로세스를 처리하도록 정의할 수 있습니다. OnCommand Workflow Automation(WFA) 워크플로우는 스토리지 설계자가 설계하고 스토리지 운영자가 실행합니다.

워크플로우 정의에는 워크플로우의 목표를 일련의 단계로 세분하는 작업이 포함됩니다. 예를 들어, NFS 볼륨을 생성하는 단계에는 다음 단계가 포함됩니다.

. 볼륨 개체 생성
. 새 엑스포트 정책을 생성하고 정책을 볼륨과 연결합니다


워크플로우의 각 단계에 WFA 명령 또는 워크플로우를 사용할 수 있습니다. WFA에는 일반 스토리지 사용 사례에 기반한 사전 정의된 명령 및 워크플로우가 포함되어 있습니다. 특정 단계에 사용할 수 있는 미리 정의된 명령 또는 워크플로를 찾을 수 없는 경우 다음 중 하나를 수행할 수 있습니다.

* 단계와 가장 일치하는 미리 정의된 명령 또는 워크플로우를 선택한 다음, 요구사항에 따라 사전 정의된 명령 또는 워크플로우를 클론 복제 및 수정합니다.
* 새 명령 또는 워크플로를 만듭니다.


그런 다음 새 워크플로에서 명령 또는 워크플로를 정렬하여 목표를 달성하는 워크플로를 만들 수 있습니다.

워크플로우 실행을 시작할 때 WFA는 실행을 계획하고 워크플로우 및 명령에 대한 입력을 사용하여 워크플로우를 실행할 수 있는지 확인합니다. 워크플로를 계획할 때 모든 리소스 선택 및 사용자 입력을 해결하여 실행 계획을 만듭니다. 계획 수립이 완료된 후 WFA는 실행 계획을 실행하며, 실행 계획은 해당 매개 변수를 포함하는 WFA 명령 세트로 구성됩니다.
