---
permalink: help/concept-how-you-map-command-parameters.html 
sidebar: sidebar 
keywords: parameter, workflow, automation, commands, specific, attribute, dictionary, entry, reference, certain, rule, aware, edit 
summary: 'WFA(Workflow Automation) 명령의 매개 변수는 특정 규칙에 따라 특정 특성 및 사전 항목 참조에 매핑됩니다. WFA 명령을 생성하거나 편집할 때 명령 매개 변수를 매핑하는 규칙을 알고 있어야 합니다.' 
---
= 명령 매개 변수를 매핑하는 방법입니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA(Workflow Automation) 명령의 매개 변수는 특정 규칙에 따라 특정 특성 및 사전 항목 참조에 매핑됩니다. WFA 명령을 생성하거나 편집할 때 명령 매개 변수를 매핑하는 규칙을 알고 있어야 합니다.

명령 매개 변수 매핑은 워크플로에서 명령 세부 정보를 정의하는 방법을 정의합니다. 명령의 매핑된 명령 매개 변수는 워크플로우 명령에 대한 명령 세부 정보를 지정할 때 탭에 표시됩니다. 탭은 매개 변수 매핑 탭의 개체 이름 열에 지정된 그룹 이름을 기반으로 이름이 지정됩니다. 워크플로에서 명령 세부 정보를 지정할 때 매핑되지 않은 매개 변수는 기타 매개 변수 탭에 표시됩니다.

명령 매개 변수 매핑에 대한 규칙은 명령 범주 및 워크플로 편집기에서 명령이 표시되는 방법을 기반으로 적용됩니다.

다음은 명령 범주입니다.

* 개체를 만드는 명령입니다
* 개체를 업데이트하는 명령입니다
* 개체를 제거하는 명령입니다
* 선택적 부모 및 자식 개체를 처리하는 명령입니다
* 개체 간의 연결을 업데이트하는 명령입니다


규칙은 각 범주에 대해 아래에 나열되어 있습니다.



== 모든 명령 범주

명령 매개 변수를 매핑할 때는 워크플로에서 명령이 사용되는 방식을 기준으로 고유 경로를 사용해야 합니다.

다음 예제에서는 자연 경로를 정의하는 방법을 보여 줍니다.

* ArrayIP 파라미터는 명령에 따라 array.ip 속성이 아닌 볼륨 사전 항목의 Aggregate.array.ip 속성을 사용해야 합니다.
+
이는 워크플로가 볼륨을 생성한 다음 생성된 볼륨을 참조하여 추가 단계를 수행할 때 중요합니다. 다음은 이와 유사한 예입니다.

+
** Qtree 사전 항목의 volume.aggregate.array.ip입니다
** LUN 사전 항목의 volume.aggregate.array.ip입니다


* 명령에 사용되는 '클러스터'의 경우 다음 중 하나를 사용해야 합니다.
+
** 볼륨 사전 항목의 vserver.cluster.primary_address입니다
** Qtree 사전 항목의 volume.vserver.cluster.primary_address






== 개체를 만드는 명령입니다

이 명령 범주는 다음 중 하나에 사용됩니다.

* 부모 개체 찾기 및 새 개체 정의
* 개체가 없는 경우 개체를 검색하고 개체를 만듭니다


이 명령 범주에 대해 다음 매개 변수 매핑 규칙을 사용해야 합니다.

* 생성된 개체의 관련 매개 변수를 개체의 사전 항목에 매핑합니다.
* 생성된 사전 항목의 참조를 통해 부모 개체를 매핑합니다.
* 새 매개 변수를 추가할 때 사전 항목에 관련 특성이 있는지 확인합니다.
+
다음은 이 규칙의 예외 시나리오입니다.

+
** 만들어진 일부 개체에는 해당 사전 항목이 없으며 부모 개체만 관련 부모 사전 항목에 매핑됩니다. 예를 들어, 배열 사전 항목에 배열만 매핑할 수 있는 * VIF* 만들기 명령-- 이 항목은 관련 부모 사전 항목에 매핑됩니다.
** 매개 변수 매핑은 필요하지 않습니다
+
예를 들어, Create or resize aggregate * 명령의 'ExecutionTimeout' 매개 변수는 매핑되지 않은 매개 변수입니다.





이 범주에는 다음과 같은 인증된 명령이 있습니다.

* 볼륨 생성
* LUN을 생성합니다




== 개체를 업데이트하는 명령입니다

이 명령 범주는 객체를 찾고 속성을 업데이트하는 데 사용됩니다.

이 명령 범주에 대해 다음 매개 변수 매핑 규칙을 사용해야 합니다.

* 사전 항목에 업데이트된 개체를 매핑합니다.
* 객체에 대해 업데이트된 매개 변수를 매핑하지 마십시오.
+
예를 들어, * 볼륨 상태 설정 * 명령에서 '볼륨' 매개 변수가 매핑되지만 새 '상태'는 매핑 해제됩니다.





== 개체를 제거하는 명령입니다

이 명령 범주는 개체를 찾아 삭제하는 데 사용됩니다.

명령에 의해 삭제된 개체를 해당 사전 항목에 매핑해야 합니다. 예를 들어, * 볼륨 제거 * 명령에서 삭제할 볼륨 은 볼륨 사전 항목의 관련 속성 및 참조에 매핑됩니다.



== 선택적 부모 및 자식 개체를 처리하는 명령입니다

이 명령 범주에 대해 다음 매개 변수 매핑 규칙을 사용해야 합니다.

* 명령의 필수 매개 변수를 명령의 선택적 매개 변수의 참조로 매핑하지 마십시오.
+
이 규칙은 명령이 특정 부모 개체의 선택적 자식 개체를 처리하는 경우에 더 관련이 있습니다. 이 경우 자식 및 부모 개체를 명시적으로 매핑해야 합니다. 예를 들어, * 중복 제거 작업 중지 * 명령에서 "어레이"와 함께 지정되거나 지정된 "어레이"의 모든 볼륨에 대해 실행 중인 중복 제거 작업을 중지합니다. 이 경우 이 명령에서 볼륨(Volume)이 선택적 매개 변수이므로 배열 매개 변수는 볼륨 배열 사전 항목이 아닌 배열 사전 항목에 직접 매핑되어야 합니다.

* 논리 수준에서 사전 항목 사이에 부모 및 자식 관계가 있지만 특정 명령의 실제 인스턴스 간에는 없는 경우 이러한 개체는 별도로 매핑되어야 합니다.
+
예를 들어, * 볼륨 이동 * 명령에서 '볼륨'은 현재 상위 애그리게이트에서 새 대상 애그리게이트로 이동됩니다. 따라서 볼륨 파라미터는 볼륨 사전 항목에 매핑되고 대상 집계 파라미터는 집계 사전 항목에 별도로 매핑되지만 volume.aggregate.name.` 으로 매핑되지 않습니다





== 개체 간의 연결을 업데이트하는 명령입니다

이 명령 범주의 경우 연관 및 객체를 관련 사전 항목에 모두 매핑해야 합니다. 예를 들어, 'vFiler에 볼륨 추가' 명령에서 '볼륨' 및 'vFiler' 매개 변수는 '볼륨' 및 'vFiler' 사전 항목의 관련 속성에 매핑됩니다.
