---
permalink: help/reference-new-command-definition-dialog-box.html 
sidebar: sidebar 
keywords: new, command, definition, dialog box, enable, define, create, workflow, predefined, meet, requirements 
summary: 새 명령 정의 대화 상자에서 새 명령을 정의할 수 있습니다. 사전 정의된 명령이 요구 사항을 충족하지 않는 경우 워크플로에 대한 새 명령을 만들 수 있습니다. 
---
= 새 명령 정의 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 명령 정의 대화 상자에서 새 명령을 정의할 수 있습니다. 사전 정의된 명령이 요구 사항을 충족하지 않는 경우 워크플로에 대한 새 명령을 만들 수 있습니다.

* 속성 탭
* 코드 탭
* 매개 변수 정의 탭
* 매개 변수 매핑 탭
* 예약 탭
* 확인 탭




== 속성 탭

이름, 설명 및 엔터티 버전과 같은 명령의 속성을 지정할 수 있습니다.

* * 이름 *
+
명령의 이름을 지정할 수 있습니다. 명령을 저장하려면 이름을 지정해야 합니다.

* * 엔터티 버전 *
+
명령에 대한 버전 번호를 major.minor.revision 형식으로 지정할 수 있습니다. 예를 들어 1.0.0과 같은 형식입니다.

* * 설명 *
+
명령에 대한 설명을 입력할 수 있습니다.

* * 문자열 표현 *
+
MVFLEX Expression Language(MVEL) 구문을 사용하여 명령에 대한 문자열 표현을 지정할 수 있습니다.

+
명령을 저장하려면 문자열 표현을 지정해야 합니다. 문자열 표현은 계획 및 실행 중에 워크플로 디자인에 명령의 세부 정보를 표시하는 데 사용됩니다. 해당 명령의 문자열 표현에는 명령의 매개 변수만 사용해야 합니다.

* * 시간 초과 *
+
명령에 대한 시간 초과 값(초)을 지정할 수 있습니다. 기본값은 600초입니다.

* * 명령 유형 *
+
명령의 실행 유형을 지정할 수 있습니다.

+
** * 표준 실행 *
+
대기 시간 없이 명령을 실행할 수 있습니다. 기본적으로 표준 실행이 선택됩니다.

** * 상태를 기다립니다 *
+
명령을 실행하기 전에 대기해야 하는 시간(초)을 지정할 수 있습니다. 기본값은 60초입니다.



* * 최소 소프트웨어 버전 *
+
명령을 실행하는 데 필요한 최소 소프트웨어 버전을 지정합니다. 예를 들어, 소프트웨어는 clustered Data ONTAP 8.2.0 및 vCenter 6.0일 수 있습니다. 버전은 쉼표로 구분된 값으로 표시됩니다.





== 코드 탭

선택한 스크립팅 언어로 명령의 코드를 입력할 수 있습니다. 스크립트 언어 드롭다운 목록에서 필요한 언어를 선택하여 새 스크립팅 언어를 추가할 수 있습니다.

* * 매개변수 검색 *
+
PowerShell 코드에 정의된 매개 변수를 매개 변수 정의 테이블과 매개 변수 매핑 테이블에 복사합니다.





== 매개 변수 정의 탭

코드 탭에 입력한 코드에 정의된 매개 변수를 표시합니다.

* * 이름 *
+
매개 변수의 이름을 표시합니다.

* * 설명 *
+
매개 변수에 대한 설명을 표시합니다.

* * 필수 *
+
필수 매개 변수에 대해 선택한 확인란을 표시합니다.

* * 유형 *
+
문자열, enum, 배열 또는 암호와 같은 매개 변수의 형식을 표시합니다.

* * 값 *
+
매개 변수에 대해 설정된 값을 표시합니다.

* * 매개 변수 추가 *
+
선택한 스크립팅 언어가 Perl인 경우 명령에 매개 변수를 추가할 수 있습니다.

* * 매개변수 제거 *
+
선택한 스크립팅 언어가 Perl인 경우 명령에서 매개 변수를 제거할 수 있습니다.





== 매개 변수 매핑 탭

매개 변수를 사전 개체에 매핑하고 특성 및 개체 이름을 지정할 수 있습니다.

* * 이름 *
+
매개 변수의 이름을 표시합니다.

* * 유형 *
+
매개 변수의 사전 개체를 선택할 수 있습니다.

* * 특성 *
+
필요한 속성을 지정할 수 있습니다. 속성을 선택하거나(사용 가능한 경우) 속성을 입력할 수 있습니다.

* * 개체 이름 *
+
사전 개체의 이름을 지정할 수 있습니다.





== 예약 탭

명령에 필요한 리소스를 예약할 수 있습니다.

* * 예약 스크립트 *
+
명령에 필요한 리소스를 예약하기 위해 SQL 쿼리를 입력할 수 있습니다. 이렇게 하면 예약된 워크플로 실행 중에 리소스를 사용할 수 있습니다.

* * 예약 표시 *
+
MVEL 구문을 사용하여 예약에 대한 문자열 표현을 지정할 수 있습니다. 문자열 표현은 예약 창에 예약 세부 정보를 표시하는 데 사용됩니다.





== 확인 탭

명령을 실행한 후 예약을 확인하고 제거할 수 있습니다.

* * 검증 스크립트 *
+
SQL 쿼리를 입력하여 예약 스크립트에서 예약한 리소스의 사용을 확인할 수 있습니다. 또한 검증 스크립트는 WFA 캐시가 업데이트되었는지 확인하고 캐시 획득 후 예약을 제거합니다.

* * 시험 확인 *
+
검증 스크립트의 매개 변수를 테스트할 수 있는 검증 대화 상자를 엽니다.





== 명령 버튼

* * 테스트 *
+
ScriptLanguage> 대화 상자에서 테스트 명령 <CommandName>을 엽니다. 이 대화 상자에서 명령을 테스트할 수 있습니다.

* * 저장 *
+
명령을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
변경 사항이 있으면 취소하고 대화 상자를 닫습니다.


