---
permalink: help/reference-edit-remote-system-type-dialog-box.html 
sidebar: sidebar 
keywords: edit, remote, system, type, dialog box, enable, modify, name, description, version, protocol, default port, timeout, existing, certified 
summary: 'Edit Remote System Type(원격 시스템 유형 편집) 대화 상자에서 이름, 설명, 버전, 프로토콜, 기본 포트를 수정할 수 있습니다. 및 기존 원격 시스템 유형의 기본 시간 초과입니다. NetApp 인증 원격 시스템 유형은 수정할 수 없습니다.' 
---
= 원격 시스템 유형 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Edit Remote System Type(원격 시스템 유형 편집) 대화 상자에서 이름, 설명, 버전, 프로토콜, 기본 포트를 수정할 수 있습니다. 및 기존 원격 시스템 유형의 기본 시간 초과입니다. NetApp 인증 원격 시스템 유형은 수정할 수 없습니다.

* 세부 정보 탭
* 검증 스크립트 탭




== 세부 정보 탭

이름, 설명, 버전 및 연결 프로토콜과 같은 원격 시스템 유형의 세부 정보를 편집할 수 있습니다.

* * 이름 *
+
원격 시스템 유형의 이름을 편집할 수 있습니다.

* * 설명 *
+
원격 시스템 유형에 대한 설명을 수정할 수 있습니다.

* * 버전 *
+
원격 시스템 유형의 버전 번호를 major.minor.revision 형식(예: 1.0.0)으로 편집할 수 있습니다.

* * 연결 프로토콜 *
+
원격 시스템에 연결할 때 OnCommand Workflow Automation(WFA)에서 사용해야 하는 다음 프로토콜 중 하나를 선택할 수 있습니다.

+
** HTTP로 폴백하는 HTTPS
+
이 연결은 주로 HTTPS를 사용합니다. HTTPS를 통한 연결에 실패하면 HTTP가 사용됩니다. HTTP를 통한 연결도 실패하면 연결 시도가 끊어집니다.

** HTTPS만 해당
** HTTP만 해당
** 맞춤형




연결 프로토콜을 선택하면 프로토콜, 기본 포트 및 기본 시간 제한(초) 필드가 데이터로 채워집니다.



== 검증 스크립트 탭

원격 시스템의 연결을 테스트하기 위한 검증 스크립트를 제공할 수 있습니다. 유효성 검사 스크립트는 Perl로 작성되어야 하며 checkCredentials($host,$user,$password,$protocol,$port, $TIMEOUT) 검증 중에 WFA는 원격 시스템 유형 및 연결 프로토콜에 대해 구성된 값으로 checkCredentials 기능을 호출합니다. 이 함수는 연결에 대한 유효성 검사에 성공한 경우 ""1"", 연결 유효성 검사에 실패한 경우 ""0"" 값을 반환합니다.

Perl 스크립트 * 테스트 를 클릭하여 연결 테스트를 위한 스크립트를 실행할 수 있습니다.



== 명령 버튼

* * 저장 *
+
원격 시스템 유형의 수정된 구성 설정을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
변경 사항이 있으면 취소하고 대화 상자를 닫습니다.


