---
permalink: help/reference-resource-selection-dialog-box.html 
sidebar: sidebar 
keywords: resource, selection, dialog box, enable, search, map, command 
summary: 자원 선택 대화 상자를 사용하면 자원을 검색하고 자원을 명령에 매핑할 수 있습니다. 
---
= 자원 선택 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
자원 선택 대화 상자를 사용하면 자원을 검색하고 자원을 명령에 매핑할 수 있습니다.

* dictionary object> by tab을 선택합니다
* 고급 탭




== dictionary object> by tab을 선택합니다

이 탭에서는 검색 기준으로 찾기 또는 필터를 지정하고 선택한 검색 조건에 대한 속성을 입력할 수 있습니다. 선택한 필터를 파인더로 저장할 수도 있습니다.

* * 필터 규칙 정의 *
+
vFiler 유닛, 애그리게이트, 가상 머신 등의 사전 항목 리소스에 대한 규칙 집합을 정의할 수 있습니다.

+
필터 규칙에는 하나 이상의 규칙 그룹이 포함될 수 있습니다.

+
규칙은 사전 항목 속성, 연산자 및 값으로 구성됩니다. 이 특성에는 해당 참조의 속성도 포함될 수 있습니다. 예를 들어, 다음과 같이 집계 규칙을 지정할 수 있습니다. ""aggr"" 문자열로 시작하는 이름의 모든 집계를 나열하고 사용 가능한 크기가 5GB보다 큽니다. 그룹의 첫 번째 규칙은 'name' 속성이고, 연산자 'tarts-with', 'aggr' 값이다. 같은 그룹에 대한 두 번째 규칙은 ""Available_size_MB"" 속성과 연산자 "">" 및 값 ""5000""입니다.

+
파인더를 선택한 경우 * 필터 규칙 정의 * 옵션이 비활성화됩니다.

+
Reset * 버튼을 클릭하여 지정된 값을 지울 수 있습니다.

* * 자연 키로 한 자원을 선택합니다 *
+
리소스의 기본 키를 기반으로 리소스를 선택할 수 있습니다.

* * 파인더 *
+
목록에서 파인더를 선택할 수 있습니다. 기본적으로 * 없음 * 이 선택되어 있습니다.

+
필터는 찾기 목록 아래에 표시됩니다. 파인더를 선택한 경우에는 필터를 선택할 수 없습니다.

* * 매개변수 *
+
선택한 찾기 또는 필터의 값을 입력할 수 있습니다. 검색 기준을 완료하려면 모든 필수 값을 입력해야 합니다.

* * 명령 버튼 *
+
** * Finder로 저장 *
+
선택한 필터를 파인더로 저장합니다.

** * 테스트 *
+
매개 변수 영역에서 값을 지정하기 전에 선택한 필터에 대한 매개 변수를 테스트할 수 있습니다.

** * OK *(확인 *)
+
설정 설정을 저장하고 대화 상자를 닫습니다.

** * 취소 *
+
변경 사항이 있으면 취소하고 대화 상자를 닫습니다.







== 고급 탭

이 탭에서는 검색을 수행할 시기를 지정하고 리소스 속성 및 리소스 속성의 상태를 정렬할 수 있습니다.

* * 이 검색을 항상 실행합니다 *
+
명령어 실행 시 제한 없이 검색을 수행한다.

* * 다음 식이 TRUE * 인 경우에만 검색을 실행합니다
+
상자에 지정된 선택적 특성의 값이 ""true""인 경우에만 검색을 실행합니다. MVFLEX Expression Language(MVEL) 구문을 사용하여 선택적 특성을 지정할 수 있습니다.

* * 테이블 정렬 *
+
선택 <사전 개체> 기준 * 탭에서 선택한 필터에 대한 속성 및 정렬 순서를 표시합니다. 정렬 순서는 리소스 선택에 중요합니다. 예를 들어 집계 정렬 순서로 내림차순을 선택한 경우 최대 "available_space"를 가진 집계가 리소스로 선택됩니다. 특성의 정렬 순서를 변경하려면 특성의 상태 열을 클릭하고 목록에서 필요한 정렬 순서를 선택합니다.

* * 명령 버튼 *
+
** * 위로 *
+
선택한 항목을 정렬 테이블에서 한 행 위로 이동합니다.

** * 아래로 *
+
선택한 항목을 정렬 테이블에서 한 행 아래로 이동합니다.




