---
permalink: help/reference-edit-workflow-window.html 
sidebar: sidebar 
keywords: workflow, window, display, select, associated, commands, parameters, blue boxes, columns, arranged, sequential, order, execution, left, right, variables, objects, gray boxes 
summary: 'Workflow <Workflow name>(작업 흐름 이름) 창에는 선택한 워크플로와 관련 명령 및 매개 변수가 표시됩니다. 워크플로와 관련된 명령은 왼쪽에서 오른쪽으로 순차적 실행 순서로 정렬된 열에 파란색 상자로 표시됩니다. 각 명령의 변수와 개체는 명령 아래에 회색 상자로 표시됩니다.' 
---
= workflow <workflow name>(워크플로 이름>) 창
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Workflow <Workflow name>(작업 흐름 이름) 창에는 선택한 워크플로와 관련 명령 및 매개 변수가 표시됩니다. 워크플로와 관련된 명령은 왼쪽에서 오른쪽으로 순서대로 정렬된 열에 파란색 상자로 표시됩니다. 각 명령의 변수와 개체는 명령 아래에 회색 상자로 표시됩니다.



== Workflow(작업 흐름) 탭

Workflow(작업 흐름) 탭에서는 하위 워크플로우와 명령을 선택 및 사용하고 표시 이름을 사용자 지정할 수 있습니다.

* * 사용 가능한 단계 *
+
사용 가능한 하위 워크플로 및 워크플로에 추가할 수 있는 명령 목록을 제공합니다.

+
이름, 구성표 및 최소 소프트웨어 버전을 텍스트 상자의 검색 문자열로 사용하여 하위 워크플로 또는 명령을 검색할 수 있습니다.

+
명령의 순서를 다시 정렬하여 워크플로 표시를 사용자 지정할 수 있습니다. 명령을 재배열하려면 명령을 필요한 순서로 끌어 놓을 수 있습니다. 명령을 두 번 클릭하면 해당 명령이 목록의 끝으로 이동합니다. 파란색 상자에서 명령의 표시 이름을 두 번 클릭하여 표시 이름을 수정할 수 있습니다. 파란색 상자 위로 커서를 이동한 다음 오른쪽 위 모서리에 있는 ""X""를 클릭하여 명령을 삭제할 수 있습니다.

+
행 번호를 클릭하여 행에서 다양한 기능을 수행할 수 있습니다.

+
** * 행을 삽입합니다 *
+
워크플로에서 선택한 행 위나 아래에 새 행을 삽입합니다.

** * 행 복사 *
+
Workflow에서 선택한 행을 복사하여 클립보드에 저장합니다. 행에 대해 설정된 반복 세부 정보는 행이 복사될 때 복사됩니다.

** * 행 반복 *
+
반복 유형을 지정할 수 있는 행 반복 세부 정보 대화 상자를 엽니다.

** * 조건 추가 *
+
행 <행 번호> 대화 상자의 조건을 엽니다. 이 대화 상자에서 조건을 선택할 수 있습니다. 선택한 조건은 행의 모든 명령에 적용할 수 있습니다. 행의 모든 명령은 선택한 조건이 충족될 경우에만 실행됩니다.

** * 행 제거 *
+
Workflow에서 선택한 행을 삭제합니다.



* * 행 붙여넣기 *
+
복사한 행을 선택한 행 위나 아래에 붙여 넣습니다. 이 옵션은 행 복사 기능을 선택한 후에 사용할 수 있습니다.





== 세부 정보 탭

세부 정보 탭에서는 워크플로에 대한 일반 정보를 제공할 수 있습니다.

* * 워크플로 이름 *
+
영숫자 문자열을 사용하여 워크플로의 이름을 지정할 수 있습니다.

* * 엔터티 버전 *
+
워크플로의 버전 번호를 jajor.minor.revision 형식(예: 1.0.0)으로 입력할 수 있습니다.

* * 범주 *
+
워크플로에 연결된 범주를 표시합니다. 범주 창에서 범주에 워크플로를 할당할 수 있습니다.

* * 워크플로 설명 *
+
워크플로에 대한 설명을 입력할 수 있습니다. 필드를 클릭하여 설명 편집 대화 상자를 열 수 있습니다.

* * 생산 준비 완료 *
+
워크플로우를 프로덕션에 사용할 준비가 되어 있는 것으로 표시하여 워크플로우를 실행하고 워크플로 창에 나열할 수 있습니다.

* * 예약된 요소 고려 *
+
선택한 리소스를 구성한 예약 만료 기간까지 워크플로에 사용할 수 있는 경우 워크플로에 예약 기능을 사용할 수 있습니다. 예약 기능을 사용하면 리소스를 선택하는 동안 다른 워크플로에서 예약한 리소스를 제외할 수 있습니다.

+

NOTE: 다른 워크플로에서 설정한 예약을 고려하지 않고 영구 캐시의 내용만 검색하도록 필터를 요청하는 경우 이 확인란을 선택하지 않아야 합니다.

* * 요소 존재 검증 활성화 *
+
요소가 있는지 확인하고 워크플로 실행 중에 특정 작업이 실패하지 않도록 할 수 있습니다. 예를 들어, 기존 볼륨과 동일한 이름의 어레이에 새 볼륨을 생성하지 않도록 할 수 있습니다.

* * 최소 소프트웨어 버전 *
+
워크플로를 실행하는 데 필요한 소프트웨어의 최소 버전을 지정합니다. 예를 들어, 소프트웨어는 clustered Data ONTAP 8.2.0 및 vCenter 6.0일 수 있습니다. 버전은 쉼표로 구분된 값으로 표시됩니다.





== 사용자 입력 탭

사용자 입력 탭에서는 Workflow 객체를 정의하고 사용자 입력을 생성할 때 생성한 사용자 입력 속성을 보고 편집할 수 있습니다. 사용자 입력 속성의 값은 워크플로를 미리 보거나 실행할 때 채워집니다.

편집할 사용자 입력을 두 번 클릭하면 변수 편집:<user_input> 대화 상자가 열리고 사용자 입력을 편집할 수 있습니다.

열 순서를 다시 정렬하여 표 표시를 사용자 지정할 수 있습니다. 열을 다시 정렬하려면 열을 필요한 순서대로 끌어서 놓을 수 있습니다. 그러나 이러한 열은 숨기거나 삭제할 수 없습니다.

* * 이름 *
+
사용자 입력 속성의 이름을 표시합니다.

* * 표시 이름 *
+
워크플로 사용자에게 표시되는 이름을 표시합니다.

* * 유형 *
+
문자열, 쿼리, 부울, 테이블 등의 사용자 입력 유형을 표시합니다. 또는 password 로 설정합니다.

* * 값 *
+
사용자 입력에 허용되는 값(예: 숫자 범위 및 문자열 정규식)을 표시합니다.

* * 기본값 *
+
사용자 입력의 기본값을 표시합니다.

* * 입력 종속성 *
+
선택한 사용자 입력에 값을 제공하는 목록의 다른 사용자 입력을 표시합니다.

* * 그룹 *
+
사용자 입력 속성에 대한 그룹의 이름을 표시합니다.

* * 필수 *
+
사용자 입력의 상태를 표시합니다. 이 확인란이 선택된 것으로 표시되면 사용자 입력 속성은 워크플로 실행을 위해 필수입니다.

* * 명령 버튼 *
+
** * 위로 *
+
선택한 항목을 테이블의 한 행 위로 이동합니다.

** * 아래로 *
+
선택한 항목을 테이블의 한 행 아래로 이동합니다.







== 상수 탭

상수 탭에서는 워크플로에서 여러 번 사용할 수 있는 상수 값을 정의할 수 있습니다. 상수 값으로 다음을 지정할 수 있습니다.

* 번호
* 문자열
* MVEL 식
* 기능
* 사용자 입력
* 변수


각 열을 정렬하고 열 순서를 다시 정렬하여 표 표시를 사용자 지정할 수 있습니다.

* * 이름 *
+
상수의 이름을 표시합니다.

* * 설명 *
+
상수에 대한 설명을 지정할 수 있습니다.

* * 값 *
+
상수 값을 지정할 수 있습니다.

* * 명령 버튼 *
+
** * 추가 *
+
Constants 테이블에 새 행을 추가합니다.

** * 제거 *
+
Constants 테이블에서 선택한 행을 삭제합니다.



+
상수를 마우스 오른쪽 단추로 클릭하여 복사 및 붙여넣기 기능을 사용할 수도 있습니다.





== Return Parameters(매개 변수 반환) 탭

매개 변수 반환 탭을 사용하면 모니터링 창 또는 웹 서비스에서 볼 수 있는 워크플로의 반환 매개 변수를 정의하고 설명을 제공할 수 있습니다.

* * 매개 변수 값 *
+
매개 변수 값을 지정할 수 있습니다.

* * 매개 변수 이름 *
+
매개 변수 이름을 지정할 수 있습니다.

* * 설명 *
+
선택한 매개 변수에 대한 설명을 지정할 수 있습니다.

* * 명령 버튼 *
+
** * 행 추가 *
+
반환 매개 변수 테이블에 새 행을 추가합니다.

** * 행 제거 *
+
Return Parameters 테이블에서 선택한 행을 삭제합니다.







== 도움말 내용 탭

도움말 콘텐츠 탭에서는 워크플로의 도움말 콘텐츠를 추가, 보기 및 제거할 수 있습니다. Workflow 도움말 내용에서는 스토리지 운영자를 위한 워크플로우에 대한 정보를 제공합니다.



== 고급 탭

고급 탭을 사용하면 API 호출을 통해 워크플로 실행을 위한 사용자 지정 URI 경로를 구성할 수 있습니다. URI 경로의 각 세그먼트는 대괄호로 묶인 워크플로의 유효한 이름 또는 문자열일 수 있습니다.

예를 들어 /DevOps/\{ProjectName}/clone을 사용할 수 있습니다. 이 워크플로는 _https:_//WFA - Server:HTTPS_port/REST/DevOps/Project1/clone/작업을 호출하는 것으로 호출할 수 있습니다.



== 명령 버튼

명령 단추는 Workflow 창 아래쪽에서 사용할 수 있습니다. 창의 오른쪽 클릭 메뉴에서 명령에 액세스할 수도 있습니다.

* * 미리보기 *
+
사용자 입력 특성을 지정할 수 있는 워크플로 미리 보기 대화 상자를 엽니다.

* * 다른 이름으로 저장 *
+
워크플로를 새 이름으로 저장할 수 있습니다.

* * 저장 *
+
설정 설정을 저장합니다.


