---
permalink: help/reference-edit-finder-dialog-box.html 
sidebar: sidebar 
keywords: edit, finder, dialog box, enable 
summary: Finder 편집 대화 상자에서 파인더를 편집할 수 있습니다. 
---
= Finder 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
Finder 편집 대화 상자에서 파인더를 편집할 수 있습니다.

* 속성 탭
* 필터
* 반환된 특성 탭




== 속성 탭

속성 * 탭을 사용하면 파인더의 이름, WFA 사전 개체의 유형 및 파인더에 대한 설명을 편집할 수 있습니다. 또한 이 탭에는 파인더에 사용된 필터의 입력 매개 변수가 표시됩니다.

* * 이름 *
+
파인더의 이름을 편집할 수 있습니다.

* * 유형 *
+
Aggregate, igroup, 클러스터 등과 같은 목록에서 WFA 사전 개체의 유형을 선택할 수 있습니다. 선택한 개체에 대한 필터가 * Filters * (필터 *) 탭에 표시됩니다.

* * 엔터티 버전 *
+
찾기 버전 번호를 major.minor.revision 형식(예: 1.0.0)으로 입력할 수 있습니다.

* * 설명 *
+
파인더에 대한 설명을 편집할 수 있습니다.

* * 입력 매개변수 표 *
+
선택한 필터의 입력 매개 변수를 표시합니다.





== 필터 탭

사용 가능한 필터 목록에서 필요한 필터를 선택할 수 있습니다.

* * 사용 가능한 필터 *
+
선택한 개체에 대해 사용 가능한 필터 목록을 * 속성 * 탭에 표시합니다.

* * 선택한 필터 *
+
사용 가능한 필터에서 선택한 필터 목록을 표시합니다.

* * 선택 버튼 *
+
선택한 항목을 한 상자에서 다른 상자로 이동합니다.





== 반환된 특성 탭

사용 가능한 필터에 대한 세부 정보를 보고 사용 가능한 필터의 필수 특성을 선택하고 속성의 정렬 순서를 지정할 수 있습니다.

* * 이용 가능 *
+
사용 가능한 필터 및 필터의 특성을 표시합니다.

* * 선택됨 *
+
선택한 필터와 특성, 별칭 및 선택한 필터의 정렬 순서를 표시합니다.

* * 명령 버튼 *
+
** * 위로 *
+
선택한 항목을 선택한 테이블의 한 행 위로 이동합니다.

** * 아래로 *
+
선택한 항목을 선택한 테이블의 한 행 아래로 이동합니다.

** * 선택 버튼 *
+
선택한 항목을 한 테이블에서 다른 테이블로 이동합니다.







== 명령 버튼

* * 테스트 *
+
편집하기 위해 선택한 파인더를 테스트할 수 있습니다.

* * 저장 *
+
변경 사항을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
는 변경 사항을 저장하지 않고 대화 상자를 닫습니다.


