---
permalink: help/reference-edit-pack-dialog-box.html 
sidebar: sidebar 
keywords: edit, pack, dialog, enable 
summary: 팩 편집 대화 상자에서 팩을 편집할 수 있습니다. 
---
= 팩 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
팩 편집 대화 상자에서 팩을 편집할 수 있습니다.

* 세부 정보 탭
* 팩 내용 탭




== 세부 정보 탭

* * 이름 *
+
이름을 입력하고 팩을 저장할 수 있습니다.

* * 버전 *
+
버전을 입력하고 팩을 저장할 수 있습니다.

* * 작성자 *
+
작성자 이름을 입력하고 팩을 저장할 수 있습니다.

* * 설명 *
+
설명을 입력하고 팩을 저장할 수 있습니다.





== 팩 내용 탭

* * 워크플로 *
+
워크플로 * 옵션을 사용하면 워크플로의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * 플린더스 *
+
Finders * 옵션을 사용하면 파인더의 * Name * 및 * Entity Version * 을 볼 수 있습니다.

* * 필터 *
+
필터 * 옵션을 사용하면 필터의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * 명령 *
+
명령 * 옵션을 사용하면 명령의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * 함수 *
+
함수 * 옵션을 사용하면 함수의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * 템플릿 *
+
템플릿 * 옵션을 사용하면 템플릿의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * 사전 *
+
사전 * 옵션을 사용하면 사전의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * 구성표 *
+
구성표 * 옵션을 사용하면 구성표의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * 캐시 쿼리 *
+
캐시 쿼리 * 옵션을 사용하면 캐시 쿼리의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * SQL 데이터 소스 형식 *
+
SQL 데이터 소스 형식 * 옵션을 사용하면 SQL 데이터 소스 형식의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * 스크립트 데이터 소스 유형 *
+
스크립트 데이터 소스 유형 * 옵션을 사용하면 스크립트 데이터 소스 유형의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * 범주 *
+
범주 * 옵션을 사용하면 범주의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.

* * 원격 시스템 유형 *
+
원격 시스템 유형 * 옵션을 사용하면 원격 시스템 유형의 * 이름 * 및 * 엔터티 버전 * 을 볼 수 있습니다.





== 명령 버튼

* * 저장 *
+
팩을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
저장하지 않고 대화 상자를 닫습니다.


