---
permalink: help/reference-new-dictionary-entry-dialog-box.html 
sidebar: sidebar 
keywords: new, dictionary, entry, dialog box, enable, create, object, specify, definition 
summary: 새 사전 항목 대화 상자에서 새 사전 개체를 만들고 개체의 정의를 지정할 수 있습니다. 
---
= 새 사전 항목 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 사전 항목 대화 상자에서 새 사전 개체를 만들고 개체의 정의를 지정할 수 있습니다.

* * 개체 유형 이름 *
+
사전 개체의 이름을 지정할 수 있습니다.

* * 설명 *
+
사전 개체에 대한 설명을 제공할 수 있습니다.

* * 구성표 *
+
오브젝트와 연관되어야 하는 스키마를 선택할 수 있습니다. 인증된 구성표에 사용자 지정 사전 항목을 추가할 수 있습니다.

* * 엔터티 버전 *
+
사전 항목의 버전 번호를 major.minor.revision 형식(예: 1.0.0)으로 입력할 수 있습니다.





== 속성 테이블

사전 개체를 정의하는 특성 목록을 지정할 수 있습니다.

* * 이름 *
+
속성 이름을 입력할 수 있습니다.

* * 유형 *
+
형식 검사를 위해 문자열, 부울 및 정수 같은 특성의 형식을 선택할 수 있습니다. 선택한 구성표의 사전 항목을 참조할 수도 있습니다.

* * 문자열 길이 *
+
속성에 대해 문자열 유형을 선택한 경우 문자열의 길이를 숫자로 지정할 수 있습니다.

* * 값 *
+
속성에 대해 enum 형식을 선택한 경우 쉼표로 구분된 값 목록을 지정할 수 있습니다.

* * 내츄럴 키 *
+
사전 특성이 사전 개체의 기본 키에 속하는지 여부를 지정할 수 있습니다.

+
기본 키는 사전 개체의 고유 식별자입니다. 예를 들어 qtree는 qtree 이름, 볼륨 이름 및 어레이 IP 주소로 식별됩니다.

* 캐시될 *
+
특성을 캐시할지 여부를 지정할 수 있습니다.

+
사전 항목에는 캐시된 속성과 캐시되지 않은 특성이 모두 포함될 수 있습니다. 캐시 테이블이 만들어지고 스키마의 캐시 획득 중에 캐싱용으로 표시된 특성으로 채워집니다. 캐시할 특성을 하나 이상 선택하면 사전 개체에 대해 캐시 테이블이 만들어집니다.

* * 는 Null일 수 있습니다 *
+
특성 값이 null일 수 있는지 여부를 지정할 수 있습니다. 이 설정은 캐시하도록 선택된 특성에 대해서만 유효합니다.

* * 설명 *
+
속성에 대한 설명을 지정할 수 있습니다.

* * 자연 키 열의 값은 대/소문자를 구분합니다 *
+
자연 키가 대/소문자를 구분하도록 지정할 수 있습니다.

* * 명령 버튼 *
+
** * 행 추가 *
+
특성을 지정하는 데 사용되는 테이블에 행을 추가할 수 있습니다.

** * 행 제거 *
+
선택한 행을 삭제할 수 있습니다.




