---
permalink: help/reference-new-data-source-dialog-box.html 
sidebar: sidebar 
keywords: new, data, source, dialog box, enable, add 
summary: 새 데이터 원본 대화 상자에서 새 데이터 원본을 추가할 수 있습니다. 
---
= 새 데이터 원본 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 데이터 원본 대화 상자에서 새 데이터 원본을 추가할 수 있습니다.



== 데이터 소스 구성 속성

* * 이름 *
+
데이터 소스의 이름을 지정할 수 있습니다.

* * 데이터 소스 유형 *
+
데이터 소스 유형(예: Active IQ Unified Manager-6.0(MySQL))을 선택할 수 있습니다.

+
데이터 소스 유형을 선택하면 포트, 구성표, 사용자 이름, 암호, 간격(분) 및 시간 제한(초) 필드는 데이터로 채워집니다.

+

NOTE: Active IQ Unified Manager 서버에서 WFA(OnCommand Workflow Automation) 데이터 보호 워크플로우를 실행하려면 Active IQ Unified Manager 서버에 WFA를 설정해야 합니다.

+
자세한 내용은 _OnCommand Unified Manager 온라인 도움말_을 참조하십시오.

* * 호스트 이름 *
+
데이터 소스에 대한 호스트 이름 또는 IP 주소(IPv4 또는 IPv6)를 지정할 수 있습니다.

+

NOTE: Active IQ Unified Manager 데이터 소스 유형은 IPv6 주소를 지원하지 않습니다.

* * 포트 *
+
선택한 데이터 소스 유형에 대해 연결된 포트 번호가 있는 경우 표시합니다.

+
기본 포트를 변경하고 데이터 소스에 다른 포트를 지정할 수 있습니다.

* * 구성표 *
+
선택한 데이터 소스 유형과 연결된 구성표를 표시합니다(예: Active IQ Unified Manager-6.0(MySQL)의 경우 _cm_storage_입니다).

+
이 속성은 수정할 수 없습니다.

* * 사용자 이름 *
+
선택한 데이터 소스 유형에 대해 연결된 사용자 이름이 있는 경우 이를 표시합니다.

+
기본 사용자 이름을 재정의하려면 이 데이터 원본에 적절한 사용자 이름을 지정해야 합니다.

+
** Active IQ Unified Manager 6.0 이상에서는 Active IQ Unified Manager 서버에서 만든 데이터베이스 사용자 계정의 사용자 이름을 입력해야 합니다.
** Performance Advisor의 경우 최소 역할이 GlobalRead인 Active IQ Unified Manager 사용자의 사용자 이름을 입력해야 합니다.


* * 암호 *
+
선택한 데이터 소스 유형에 대한 암호를 지정할 수 있습니다.

+
이 데이터 소스의 사용자 이름에 대한 기본 암호를 무시하려면 암호를 지정해야 합니다.

+
** Active IQ Unified Manager 6.0 이상에서는 Active IQ Unified Manager 서버에서 만든 데이터베이스 사용자 계정의 암호를 입력해야 합니다.
** Performance Advisor의 경우 Active IQ Unified Manager 사용자의 암호를 입력해야 하며, 최소 역할은 GlobalRead여야 합니다.


* * 데이터베이스 *
* * 간격(분) *
+
값을 클릭하고 위쪽 및 아래쪽 화살표를 사용하여 간격(분)을 선택할 수 있습니다.

+

NOTE: 간격이 영(0)으로 설정된 경우 자동 샘플링이 비활성화됩니다.

+
데이터 샘플링의 기본 간격은 다음과 같습니다.

+
** 스크립트 기반 데이터 소스 유형: 1440(성능 및 VC)
** SQL 기반 데이터 소스 유형: 30(cm_storage, storage 및 cm_performance)


* * 설치 지침 안내서 * 를 참조하십시오
+
데이터 원본 설정에 대한 지침을 지정할 수 있는 설치 지침 안내서 대화 상자를 엽니다.





== 명령 버튼

* * 저장 *
+
설정 설정을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
변경 사항이 있으면 취소하고 대화 상자를 닫습니다.


