---
permalink: help/reference-new-credentials-dialog-box.html 
sidebar: sidebar 
keywords: new, credential, dialog box, enable, create 
summary: 새 자격 증명 대화 상자에서 새 자격 증명을 생성할 수 있습니다. 
---
= 새 자격 증명 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 자격 증명 대화 상자에서 새 자격 증명을 생성할 수 있습니다.



== 자격 증명 매개 변수입니다

새로 생성된 자격 증명에 대해 다음 매개 변수를 설정할 수 있습니다.

* 일치 *
+
자격 증명의 일치 유형을 선택할 수 있습니다. 자격 증명은 특정 IP 주소 또는 호스트 이름 또는 전체 서브넷 또는 IP 범위에 대한 자격 증명을 정의합니다. 다음 옵션 중 하나를 선택할 수 있습니다.

+
** Exact(정확히 일치): 특정 IP 또는 호스트 이름에 대한 자격 증명을 정의합니다
** 패턴: 호스트 이름 범위 또는 전체 서브넷 또는 IP 범위에 대한 자격 증명을 정의합니다
+
pattern 은 문자열을 일치시키는 데 사용되는 정규식입니다. 예를 들어 10.10.10.10은 10.10.10.10.0 ~ 10.10.255 범위의 IP를 일치시키고 host는 host로 시작하는 모든 호스트 이름을 일치시킵니다.



* * 유형 *
+
드롭다운 목록에서 호스트 유형을 선택할 수 있습니다.

+

NOTE: Linux에서는 VMware vCenter가 지원되지 않습니다.

* * 이름/IP *
+
자격 증명의 호스트 이름 또는 IP 주소를 지정할 수 있습니다.

* * 사용자 이름 *
+
자격 증명의 사용자 이름을 지정할 수 있습니다.

* * 암호 *
+
자격 증명에 대해 만든 사용자 이름에 대한 암호를 지정할 수 있습니다.

* * 기본값 덮어쓰기 *
+
자격 증명에 대해 선택한 원격 시스템 유형과 연결된 프로토콜, 포트 및 시간 초과의 기본값을 덮어쓸 수 있습니다.

+
기본적으로 이 확인란은 선택되어 있지 않습니다. 기본값을 덮어쓰려면 이 확인란을 선택해야 합니다.





== 명령 버튼

* * 테스트 *
+
필요한 자격 증명을 사용하여 로그인하여 호스트 또는 IP 주소에 대한 연결을 테스트할 수 있습니다.

* * 저장 *
+
구성 설정을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
변경 사항이 있으면 취소하고 대화 상자를 닫습니다.


