---
permalink: help/reference-edit-variable-dialog-box.html 
sidebar: sidebar 
keywords: edit, variable, dialog box, enable, user, input, attributes, workflow 
summary: '변수 편집:<UserInputName> 대화 상자에서 워크플로의 사용자 입력 특성을 편집할 수 있습니다.' 
---
= 변수 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
변수 편집:<UserInputName> 대화 상자에서 워크플로의 사용자 입력 특성을 편집할 수 있습니다.



== 속성

* * 변수 이름 *
+
사용자 입력의 이름을 편집할 수 있습니다. 사용자 입력의 이름을 바꾸면 워크플로의 사용자 입력에 대한 모든 참조가 업데이트됩니다.

* * 표시 이름 *
+
사용자 입력의 표시 이름을 지정하거나 편집할 수 있습니다. 유사한 이름의 사용자 입력 속성을 만든 경우 고유한 표시 이름을 지정할 수 있습니다.

* * 설명 *
+
사용자 입력에 대한 설명을 지정하거나 편집할 수 있습니다. 워크플로를 실행하거나 미리 볼 때 설명이 도구 설명으로 나타납니다.

* * 유형 *
+
사용자 입력 유형을 선택할 수 있습니다. 선택한 옵션에 따라 필드나 대화 상자 링크가 표시됩니다. 사용 가능한 옵션은 다음과 같습니다.

+
** String: Regex 필드에 유효한 값에 대한 정규식을 입력할 수 있습니다(예: *).
** 번호: 범위 필드에 숫자 범위를 입력할 수 있습니다(예: 1 - 15).
** Enum: Enum Values 필드에 닫힌 값 목록을 입력할 수 있습니다.
** 쿼리: 결과를 얻기 위해 간단한 SQL 쿼리를 입력할 수 있습니다.
+
사용자는 결과의 첫 번째 열에 있는 값만 선택할 수 있습니다.

** 쿼리(다중 선택): 값 목록을 가져오는 SQL 쿼리를 입력할 수 있습니다.
+
사용자는 워크플로를 실행하는 동안 단일 값 또는 여러 값을 선택할 수 있습니다. 예를 들어, 공유 및 내보내기가 포함된 단일 볼륨, 여러 볼륨 또는 볼륨을 선택할 수 있습니다.

+
결과에 표시된 열에서 값을 선택할 수 있습니다. 행을 선택하면 선택한 행의 모든 열에서 값이 선택됩니다.

** 부울: 사용자 입력 대화 상자에 확인란을 표시할 수 있습니다.
** 표: 워크플로를 실행하는 동안 여러 값을 입력하는 데 사용할 수 있는 테이블의 열 머리글을 지정할 수 있습니다. 예를 들어 노드 이름과 포트 이름 목록을 지정하는 데 사용할 수 있는 테이블을 지정할 수 있습니다.
+
또한 열 사용자 입력의 유형과 열 사용자 입력과 관련된 속성을 구성할 수 있습니다. 선택한 사용자 입력 유형에 따라 대화 상자가 표시됩니다. 사용 가능한 옵션은 다음과 같습니다.

+
*** String: Regex 필드에 유효한 값에 대한 정규식을 입력할 수 있습니다(예: *).
*** 번호: 범위 필드에 숫자 범위를 입력할 수 있습니다(예: 1 - 15).
*** Enum: Enum Values 필드에 닫힌 값 목록을 입력할 수 있습니다.
*** 쿼리: 결과를 얻기 위해 간단한 SQL 쿼리를 입력할 수 있습니다.
+
사용자는 결과의 첫 번째 열에 있는 값만 선택할 수 있습니다. 테이블 사용자 입력 열의 쿼리는 쿼리 내의 다른 사용자 입력을 참조할 수 없습니다.

*** 부울: 드롭다운 목록에서 부울 값으로 ""true" 또는 ""false""를 선택할 수 있습니다.


** 암호: 사용자가 입력한 암호를 암호화할 수 있습니다.
+
암호화된 암호는 WFA 애플리케이션 및 로그 파일에 걸쳐 별표 문자 시퀀스로 표시됩니다.

** 사전: 선택한 사전 항목에 대한 테이블 데이터를 추가할 수 있습니다.
+
사전 항목 속성은 반환할 속성을 선택합니다. 워크플로를 실행하는 동안 단일 값 또는 여러 값을 선택할 수 있습니다. 예를 들어 공유 및 내보내기가 포함된 단일 볼륨, 여러 볼륨 또는 볼륨을 선택할 수 있습니다. 기본적으로 단일 값이 선택됩니다. 필터링할 규칙을 선택할 수도 있습니다. 규칙은 사전 항목 속성, 연산자 및 값으로 구성됩니다. 이 특성에는 해당 참조의 속성도 포함될 수 있습니다. 예를 들어, 이름이 ""aggr""이고 사용 가능한 크기가 5GB보다 큰 모든 애그리게이트를 나열하여 집계에 대한 규칙을 지정할 수 있습니다. 그룹의 첫 번째 규칙은 이름, 연산자 'tarts-with', 값 kaggr입니다. 같은 그룹에 대한 두 번째 규칙은 연산자 > 와 값 5000을 가진 속성 Available_size_MB 입니다.



* * 값 잠금 *
+
사용자가 쿼리 반환 값 이외의 값을 입력할 수 있는지 여부를 지정할 수 있습니다. 이 확인란을 선택하면 사용자가 값을 제공할 수 없으며 쿼리 반환 값만 선택할 수 있습니다. 이 옵션은 Enum 및 Query 유형 옵션과 함께 사용됩니다.

* * 기본값 *
+
사용자 입력의 기본값을 설정할 수 있습니다.

* * 필수 *
+
워크플로우 실행에 사용자 입력이 필수인지 여부를 지정할 수 있습니다.





== 그룹

* * 그룹 이름 *
+
관련된 사용자 입력 특성을 함께 그룹화할 수 있습니다. 사용자 입력 속성은 워크플로를 미리 보거나 실행할 때 정의한 그룹으로 표시됩니다. 예를 들어 볼륨 세부 사항과 관련된 사용자 입력 특성을 함께 그룹화할 수 있습니다.

* * 기본적으로 그룹을 확장합니다 *
+
그룹에 지정된 모든 사용자 입력 특성을 확장된 목록으로 표시할 수 있습니다. 이 확인란을 선택하지 않으면 사용자 입력 그룹이 축소된 상태로 표시됩니다.





== 종속성

다른 사용자 입력에 대해 입력된 값을 기반으로 사용자 입력을 활성화할 수 있습니다. 예를 들어 NAS 프로토콜을 구성하는 워크플로우에서 프로토콜에 필요한 사용자 입력을 ""NFS""로 지정하여 "read-write host list""user input" 또는 ""cifs""를 설정하여 ""cifs acl configuration""을 활성화할 수 있습니다.

* * 의존할 사용자 입력을 선택하십시오 *
+
변수 이름 필드에 표시되는 사용자 입력을 활성화하는 데 필요한 사용자 입력을 선택할 수 있습니다.

* * 해당 값(쉼표로 구분) *
+
변수 이름 필드에 사용자 입력을 표시할 수 있는 조건부 사용자 입력 값을 지정할 수 있습니다.


