---
permalink: help/reference-new-user-dialog-box.html 
sidebar: sidebar 
keywords: new, user, dialog box, enable, create, account 
summary: 새 사용자 대화 상자에서 새 사용자 계정을 만들 수 있습니다. 
---
= 새 사용자 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 사용자 대화 상자에서 새 사용자 계정을 만들 수 있습니다.

* * 사용자 이름 *
+
사용자 이름을 지정합니다.

* * 역할 *
+
다음 사용자 역할 중 하나를 선택할 수 있습니다.

+
** 게스트: 이 사용자는 워크플로 실행 상태만 보거나 워크플로 실행 상태의 변경 사항에 대한 알림을 받을 수 있습니다.
** 연산자: 이 사용자는 액세스 권한이 있는 워크플로우를 미리 보고 실행할 수 있습니다.
** 설계자: 이 사용자는 워크플로우를 생성할 수 있는 모든 액세스 권한을 가지고 있지만, 글로벌 WFA 서버 설정을 수정할 수 없습니다.
** 관리자: 이 사용자는 WFA 서버에 완전히 액세스할 수 있습니다.
** 백업: 이 사용자는 WFA 서버의 백업을 원격으로 생성할 수 있는 유일한 사용자입니다. 하지만 사용자는 다른 모든 액세스에서는 제한됩니다.


* * 이메일 *
+
알림 설정 옵션이 선택된 경우 알림을 보낼 사용자의 이메일 주소를 지정할 수 있습니다.

* * 암호 *
+
사용자의 암호를 지정합니다.

* * 확인 *
+
암호를 다시 지정합니다.

* * 알림 켜짐 *
+
계정 사용자에게 이메일로 통지해야 하는 시기를 선택할 수 있습니다. 워크플로 실행 상태 알림은 사용자가 실행하는 워크플로에만 적용됩니다. 다음 옵션 중 원하는 조합을 선택할 수 있습니다.

+
** 워크플로 실행 시작됨: 워크플로 실행이 시작될 때 사용자에게 알립니다.
** 워크플로 실행 실패/부분적으로 성공: 워크플로 실행이 실패하거나 하나 이상의 단계가 실패해도 워크플로가 성공적으로 실행된 경우 사용자에게 알립니다.
+
실패한 단계가 구성되어 단계가 실패한 경우에도 워크플로우 실행이 계속되도록 하기 때문에 실행이 완료됩니다.

** 워크플로 실행이 성공적으로 완료됨: 워크플로 실행이 성공적으로 완료되면 사용자에게 알립니다.
** 워크플로우 실행 승인 대기 중: WFA 구성 설정에 따라 워크플로우 실행이 운영자 또는 설계자의 승인을 대기 중인 경우 사용자에게 알려줍니다.
** 획득 실패: 데이터 소스에 대한 데이터 획득이 실패할 때 사용자에게 알립니다.
+
이 옵션은 Admin 및 Architect 사용자에게만 활성화됩니다.







== 명령 버튼

* * 저장 *
+
구성 설정을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
변경 사항이 있으면 취소하고 대화 상자를 닫습니다.


