---
permalink: help/reference-edit-user-dialog-box.html 
sidebar: sidebar 
keywords: edit, user, dialog box, enable, view, modify, account, settings 
summary: 사용자 편집 대화 상자에서 사용자 계정 설정을 보고 수정할 수 있습니다. 
---
= 사용자 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
사용자 편집 대화 상자에서 사용자 계정 설정을 보고 수정할 수 있습니다.

계정 권한 및 역할에 따라 사용자 창에 액세스하지 못할 수도 있습니다. 그러나 * 설정 * 을 선택하고 * 관리 * 에서 * 계정 설정 * 을 클릭하여 계정 설정을 편집할 수 있습니다.


NOTE: 편집 가능한 필드는 할당된 역할 및 계정 권한에 따라 다릅니다.

* * 이름 *
+
사용자 계정의 사용자 이름을 표시합니다.

* * 역할 *
+
사용자 계정에 할당된 역할을 표시합니다.

* * 이메일 *
+
알림 설정 옵션을 선택한 경우 알림을 보낼 사용자 계정의 이메일을 지정합니다.

* * 암호 변경 *
+
사용자 계정의 현재 암호를 변경할 수 있습니다. 이 확인란을 선택하면 다음 필드가 필요합니다.

+
** 새 암호* -- 새 암호를 지정합니다.
** * 확인 * -- 새 암호를 다시 지정합니다.


* * 알림 켜짐 *
+
워크플로 실행 중에 계정 사용자에게 전자 메일로 알림을 보낼 시기를 선택할 수 있습니다. 이 확인란을 선택하면 다음 옵션 중 원하는 조합을 선택할 수 있습니다.

+
** 워크플로 실행 시작됨: 워크플로 실행이 시작될 때 사용자에게 알립니다.
** 워크플로 실행 실패/부분적으로 성공: 워크플로 실행이 실패하거나 하나 이상의 단계가 실패해도 워크플로가 성공적으로 실행된 경우 사용자에게 알립니다.
+
실패한 단계가 구성되어 단계가 실패한 경우에도 워크플로우 실행이 계속되도록 하기 때문에 실행이 완료됩니다.

** 워크플로 실행이 성공적으로 완료됨: 워크플로 실행이 성공적으로 완료되면 사용자에게 알립니다.
** 워크플로우 실행 승인 대기 중: WFA 구성 설정에 따라 워크플로우 실행이 운영자 또는 설계자의 승인을 대기 중인 경우 사용자에게 알려줍니다.
** 획득 실패: 데이터 소스에 대한 데이터 획득이 실패할 때 사용자에게 알립니다.
+
이 옵션은 Admin 및 Architect 사용자에게만 활성화됩니다.







== 명령 버튼

* * 저장 *
+
구성 설정을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
변경 사항이 있으면 취소하고 대화 상자를 닫습니다.


