---
permalink: help/reference-new-finder-dialog-box.html 
sidebar: sidebar 
keywords: new, finder, dialog box, enable, create 
summary: 새 찾기 대화 상자에서 새 파인더를 만들 수 있습니다. 
---
= 새 찾기 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 찾기 대화 상자에서 새 파인더를 만들 수 있습니다.

* 속성 탭
* 필터
* 반환된 특성 탭




== 속성 탭

속성 * 탭을 사용하면 파인더의 이름을 지정하고 WFA 사전 개체의 유형을 선택한 다음 파인더에 대한 설명을 입력할 수 있습니다. 이 탭은 * Filters * (필터 *) 탭에서 필터를 선택한 후 입력 매개 변수도 표시합니다.

* * 이름 *
+
파인더의 이름을 입력할 수 있습니다.

* * 유형 *
+
Aggregate, igroup, 클러스터 등과 같은 목록에서 오브젝트 유형을 선택할 수 있습니다. 선택한 개체에 대한 필터가 * Filters * (필터 *) 탭에 표시됩니다.

* * 엔터티 버전 *
+
찾기 버전 번호를 major.minor.revision 형식(예: 1.0.0)으로 입력할 수 있습니다.

* * 설명 *
+
파인더에 대한 설명을 입력할 수 있습니다.

* * 입력 매개변수 표 *
+
선택한 필터에 대한 입력 매개변수를 표시합니다.





== 필터 탭

사용 가능한 필터 목록에서 필요한 필터를 선택할 수 있습니다.

* * 사용 가능한 필터 *
+
선택한 개체에 대해 사용 가능한 필터 목록을 * 속성 * 탭에 표시합니다.

* * 선택한 필터 *
+
사용 가능한 필터에서 선택한 필터 목록을 표시합니다.

* * 선택 버튼 *
+
선택한 항목을 한 상자에서 다른 상자로 이동합니다.





== 반환된 특성 탭

사용 가능한 필터에 대한 세부 정보를 보고 사용 가능한 필터의 필수 특성을 선택하고 속성의 정렬 순서를 지정할 수 있습니다.

* * 이용 가능 *
+
사용 가능한 필터 및 필터의 특성을 표시합니다.

* * 선택됨 *
+
선택한 필터와 특성, 별칭 및 선택한 필터의 정렬 순서를 표시합니다.

* * 명령 버튼 *
+
** * 위로 *
+
선택한 항목을 선택한 테이블의 한 행 위로 이동합니다.

** * 아래로 *
+
선택한 항목을 선택한 테이블의 한 행 아래로 이동합니다.

** * 선택 버튼 *
+
선택한 항목을 한 테이블에서 다른 테이블로 이동합니다.







== 명령 버튼

* * 테스트 *
+
정의한 파인더를 테스트할 수 있습니다.

* * 저장 *
+
파인더를 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
는 파인더를 저장하지 않고 대화 상자를 닫습니다.


