---
permalink: help/reference-edit-data-source-dialog-box.html 
sidebar: sidebar 
keywords: edit, data, source, dialog box, enable, modify, existing 
summary: 데이터 원본 편집 대화 상자에서 기존 데이터 원본을 수정할 수 있습니다. 
---
= 데이터 원본 편집 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
데이터 원본 편집 대화 상자에서 기존 데이터 원본을 수정할 수 있습니다.



== 데이터 소스 구성 속성

* * 이름 *
+
데이터 소스의 이름을 수정할 수 있습니다.

* * 데이터 소스 유형 *
+
데이터 소스의 데이터 소스 유형을 표시합니다. 이 필드는 수정할 수 없습니다.

* * 호스트 이름 *
+
데이터 소스에 대한 호스트 이름 또는 IP 주소(IPv4 또는 IPv6)를 지정할 수 있습니다.

+

NOTE: Active IQ Unified Manager 데이터 소스 유형은 IPv6 주소를 지원하지 않습니다.

* * 포트 *
+
선택한 데이터 소스 유형에 대해 연결된 포트 번호가 있는 경우 표시합니다. 데이터 소스의 기본 포트 번호를 변경할 수 있습니다.

* * 구성표 *
+
선택한 데이터 소스 유형과 연결된 구성표를 표시합니다(예: Unified Manager-6.0(MySQL)의 경우 _cm_storage_).

+
이 속성은 수정할 수 없습니다.

* * 사용자 이름 *
+
선택한 데이터 소스 유형에 대해 연결된 사용자 이름이 있는 경우 이를 표시합니다.

+
기본 사용자 이름을 재정의하려면 이 데이터 원본에 적절한 사용자 이름을 지정해야 합니다.

+
** 6.0 이전 버전의 Unified Manager에서는 ocsetup을 실행하는 동안 기본 자격 증명을 재정의하는 데 사용한 사용자 이름을 입력해야 합니다.
** Unified Manager 6.0 이상에서는 Unified Manager 서버에서 만든 데이터베이스 사용자 계정의 사용자 이름을 입력해야 합니다.
** Performance Advisor의 경우 최소 역할이 GlobalRead인 Active IQ Unified Manager 사용자의 사용자 이름을 입력해야 합니다.


* * 암호 *
+
선택한 데이터 소스 유형에 대한 암호를 지정할 수 있습니다.

+
이 데이터 소스의 사용자 이름에 대한 기본 암호를 무시하려면 암호를 지정해야 합니다.

+
** 6.0 이전 버전의 Unified Manager에서는 ocsetup을 실행하는 동안 기본 자격 증명을 재정의하는 데 사용한 암호를 입력해야 합니다.
** Unified Manager 6.0 이상에서는 서버에 만든 데이터베이스 사용자 계정의 암호를 입력해야 합니다.
** Performance Advisor의 경우 GlobalRead 이상의 역할을 가진 Unified Manager 사용자의 암호를 입력해야 합니다.


* * 데이터베이스 *
+
선택한 데이터 소스 유형에 대해 연결된 데이터베이스 이름이 있는 경우 이를 표시합니다.

* * 간격(분) *
+
값을 클릭하고 위쪽 및 아래쪽 화살표를 사용하여 간격(분)을 선택할 수 있습니다.

+

NOTE: 간격이 영(0)으로 설정된 경우 자동 샘플링이 비활성화됩니다.

+
데이터 샘플링의 기본 간격은 다음과 같습니다.

+
** 스크립트 기반 데이터 소스 유형: 1440(성능 및 VC)
** SQL 기반 데이터 소스 유형: 30(cm_storage, storage 및 cm_performance)


* * 설치 지침 안내서 * 를 참조하십시오
+
데이터 원본을 설정하는 단계를 설명하는 설치 지침 안내서 대화 상자를 엽니다.





== 명령 버튼

* * 구성표 재설정 *
+
구성표 재설정 확인 대화 상자를 엽니다. 이 대화 상자에서는 다음 데이터 획득 중에 발생하는 선택한 구성표의 캐시 스토리지를 재설정할 수 있습니다.

+

IMPORTANT: 재설정 프로세스는 모든 테이블을 포함하여 캐시된 모든 데이터를 삭제합니다. 전체 캐시는 다음 데이터 획득 시 처음부터 구축됩니다.

* * 저장 *
+
설정 설정을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
변경 사항이 있으면 취소하고 대화 상자를 닫습니다.


