---
permalink: help/reference-new-active-directory-group-dialog-box.html 
sidebar: sidebar 
keywords: active, directory, group, enable, create, new, oncommand, workflow, automation 
summary: 새 Active Directory 그룹 대화 상자에서 새 OnCommand Workflow Automation Active Directory 그룹을 만들 수 있습니다. 
---
= 새 Active Directory 그룹 대화 상자
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
새 Active Directory 그룹 대화 상자에서 새 OnCommand Workflow Automation Active Directory 그룹을 만들 수 있습니다.

* * 그룹 이름 *
+
그룹 이름을 지정합니다.

* * 역할 *
+
다음 그룹 역할 중 하나를 선택할 수 있습니다.

+
** * 게스트 *
+
이 그룹은 워크플로 실행의 상태만 보거나 워크플로 실행 상태의 변경 사항에 대한 알림을 받을 수 있습니다.

** * 연산자 *
+
이 그룹은 그룹에 액세스 권한이 제공되는 워크플로우를 미리 보고 실행할 수 있습니다.

** * 승인자 *
+
이 그룹은 그룹에 액세스 권한이 제공되는 워크플로우를 미리 보고, 실행하고, 승인하고, 거부할 수 있습니다.

+

NOTE: 승인자의 이메일 ID와 승인자에게 통지될 워크플로의 상태를 제공해야 합니다. 승인자가 여러 개인 경우 * 이메일 * 필드에 그룹 이메일 ID를 제공할 수 있습니다.

** * 설계자 *
+
이 그룹은 워크플로우 생성을 위한 모든 액세스 권한을 가지고 있지만 글로벌 WFA 서버 설정을 수정할 수 없습니다.

** * 관리자 *
+
이 그룹은 WFA 서버에 대한 모든 액세스 권한을 가지고 있습니다.

+

NOTE: 관리자 그룹을 하나 이상 구성해야 합니다.



* * 이메일 *
+
알림 켜짐 * 옵션을 선택한 경우 알림을 보낼 그룹의 이메일 주소를 지정할 수 있습니다.

* * 알림 켜짐 *
+
Active Directory 그룹에 e-메일을 통해 알림을 보내는 시기를 선택할 수 있습니다. 워크플로 실행 상태 알림은 그룹이 실행하는 워크플로에만 적용됩니다. 다음 옵션 중 원하는 조합을 선택할 수 있습니다.

+
** 워크플로 실행 시작됨: 워크플로 실행이 시작될 때 그룹에 알립니다.
** 워크플로 실행 실패/부분 성공: 워크플로 실행이 실패하거나 하나 이상의 단계가 실패해도 워크플로가 성공적으로 실행된 경우 그룹에 알립니다.
+
실패한 단계가 단계가 실패한 경우에도 워크플로우 실행이 계속되도록 구성되었기 때문에 실행이 완료됩니다.

** 워크플로 실행이 성공적으로 완료되었습니다. 워크플로 실행이 성공적으로 완료되면 그룹에 알립니다.
** 승인 대기 중인 워크플로우 실행: WFA 구성 설정에 따라 워크플로우 실행이 승인자, 설계자 또는 운영자 그룹의 승인을 대기 중인 경우 그룹에 알립니다.






== 명령 버튼

* * 저장 *
+
구성 설정을 저장하고 대화 상자를 닫습니다.

* * 취소 *
+
변경 사항이 있으면 취소하고 대화 상자를 닫습니다.


