---
permalink: workflows/concept-how-entity-versioning-works.html 
sidebar: sidebar 
keywords: oncommand, workflow, automation, entities, commands, version number, easily, manage, change 
summary: '명령 및 워크플로우와 같은 WFA(OnCommand Workflow Automation) 엔터티의 버전은 분산됩니다. 버전 번호를 사용하여 WFA 엔터티의 변경 사항을 쉽게 관리할 수 있습니다.' 
---
= 엔터티 버전 관리 작동 방식
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
명령 및 워크플로우와 같은 WFA(OnCommand Workflow Automation) 엔터티의 버전은 분산됩니다. 버전 번호를 사용하여 WFA 엔터티의 변경 사항을 쉽게 관리할 수 있습니다.

각 WFA 엔터티에는 1.1.20과 같이 'jor.minor.revision' 형식의 버전 번호가 포함되어 있습니다. 버전 번호의 각 부분에 최대 3자리 숫자를 포함할 수 있습니다.

WFA 엔터티의 버전 번호를 수정하기 전에 다음 규칙을 알고 있어야 합니다.

* 버전 번호는 현재 버전에서 이전 버전으로 변경할 수 없습니다.
* 버전 각 부분은 0에서 999 사이의 숫자여야 합니다.
* 새로운 WFA 엔터티의 버전은 기본적으로 1.0.0으로 관리됩니다.
* 개체의 버전 번호는 복제 시 또는 * 다른 이름으로 저장 * 을 사용하여 개체의 복사본을 저장할 때 유지됩니다.
* WFA 설치 버전에는 여러 버전의 엔터티가 포함되어 있을 수 없습니다.


WFA Entity의 버전을 업데이트하면 해당 상위 엔터티의 버전이 자동으로 업데이트됩니다. 예를 들어, * 볼륨 생성 * 명령의 버전을 업데이트하면 * NFS 볼륨 생성 * 워크플로우가 * 볼륨 생성 * 명령의 직접적인 상위 엔터티이므로 * NFS 볼륨 생성 * 워크플로가 업데이트됩니다. 버전에 대한 자동 업데이트는 다음과 같이 적용됩니다.

* 엔티티의 주 버전을 수정하면 직접 실행 모체 엔티티의 부 버전이 업데이트됩니다.
* 요소의 부 버전을 수정하면 직접 실행 모체 요소의 수정본 버전이 업데이트됩니다.
* 요소의 수정본 버전을 수정해도 그 직계 모체 요소의 버전 일부가 업데이트되지 않습니다.


다음 표에는 WFA 엔터티와 해당 상위 엔터티가 나와 있습니다.

[cols="2*"]
|===
| 요소 | 직접 모체 요소 


 a| 
캐시 쿼리입니다
 a| 
* 데이터 소스 유형입니다




 a| 
템플릿
 a| 
* 워크플로우




 a| 
기능
 a| 
* 워크플로우
* 템플릿



NOTE: 함수에 특수 또는 혼합 대/소문자 문자가 포함된 경우 해당 상위 요소의 직접 버전은 업데이트되지 않을 수 있습니다.



 a| 
사전
 a| 
* 템플릿
* 필터
* 캐시 쿼리입니다
* 명령
* 스크립트 메서드를 사용하는 데이터 소스 유형입니다




 a| 
명령
 a| 
* 워크플로우




 a| 
필터
 a| 
* 파인더
* 워크플로우




 a| 
파인더
 a| 
* 워크플로우




 a| 
데이터 소스 유형입니다
 a| 
없음



 a| 
워크플로우
 a| 
없음

|===
WFA에서 버전 번호의 일부 또는 전체 버전 번호를 사용하여 엔터티를 검색할 수 있습니다.

모체 요소를 삭제하면, 종속 요소는 보존되고 해당 버전은 삭제 대상으로 업데이트되지 않습니다.



== 엔터티를 가져올 때 버전 관리 작동 방식

Workflow Automation 2.2 이전 버전에서 요소를 가져오면 기본적으로 엔터티의 버전이 1.0.0으로 지정됩니다. 가져온 엔터티가 WFA 서버에 이미 있는 경우 가져온 엔터티로 기존 엔터티를 덮어씁니다.

가져오는 동안 WFA 엔터티가 변경될 수 있습니다.

* 요소 업그레이드
+
요소가 최신 버전으로 대치됩니다.

* 요소 롤백
+
요소가 이전 버전으로 대치됩니다.

+

NOTE: 요소의 롤백을 수행하면 해당 인접 상위 요소의 버전이 업데이트됩니다.

* 새 요소 불러오기



NOTE: '.dar' 파일에서 요소를 선택적으로 불러올 수 없습니다.

요소의 차기 버전을 불러오면, 즉시 모체 요소의 버전이 업데이트됩니다.

불러온 모체 요소에 여러 개의 종속 요소가 있을 경우, 종속 요소에 대한 가장 높은 변경 수준(주, 부 또는 수정본)만 모체 요소에 적용됩니다. 다음 예에서는 이 규칙의 작동 방식을 설명합니다.

* 불러온 모체 요소의 경우, 사소한 변경 사항이 있는 종속 요소와 수정본이 변경된 다른 종속 요소가 있으면, 모체 요소에 사소한 변경 사항이 적용됩니다.
+
모체 버전의 수정본 부분이 증가합니다.

* 불러온 모체 요소의 경우, 주요 변경 사항이 있는 종속 요소와 사소한 변경 사항이 있는 다른 종속 요소가 있으면, 주요 변경 사항이 모체 요소에 적용됩니다.
+
상위 버전의 부 부분이 증가합니다.





== 불러온 하위 요소의 버전이 상위 버전의 영향을 받는 방법의 예

WFA에서 다음 워크플로우를 고려하십시오. "'Create Volume and export using NFS-Custom' 1.0.0.

워크플로에 포함된 기존 명령은 다음과 같습니다.

* 수출정책 만들기-사용자 정의 1.0.0
* Create Volume - Custom" 1.0.0


가져올 .dar 파일에 포함된 명령어는 다음과 같다.

* 수출정책 만들기-사용자지정 1.1.0
* Create Volume - Custom" 2.0.0


이 ".dar" 파일을 가져오면 "'Create Volume and export using NFS-Custom'" 워크플로우의 부 버전이 1.1.0으로 증가합니다.
