---
permalink: workflows/reference-guidelines-for-workflows.html 
sidebar: sidebar 
keywords: aware, guidelines, create, modify, predefined, workflow, oncommand, workflow, automation 
summary: 'WFA(OnCommand Workflow Automation)에 대해 미리 정의된 워크플로우를 생성하거나 수정하기 위한 지침에 대해 알고 있어야 합니다.' 
---
= 워크플로 지침
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA(OnCommand Workflow Automation)에 대해 미리 정의된 워크플로우를 생성하거나 수정하기 위한 지침에 대해 알고 있어야 합니다.



== 일반 지침

[cols="2*"]
|===
| 지침 | 예 


 a| 
스토리지 운영자가 실행하는 작업을 반영하도록 워크플로의 이름을 지정합니다.
 a| 
CIFS 공유를 생성합니다



 a| 
워크플로 이름의 경우 첫 번째 단어와 개체인 모든 단어의 첫 글자를 대문자로 표시합니다. 약어 및 머리글자의 대문자로 표시합니다.
 a| 
볼륨

qtree입니다

Clustered Data ONTAP 트리 CIFS 공유를 생성합니다



 a| 
워크플로 설명의 경우 필수 조건, 워크플로의 결과 또는 실행 조건적 측면을 포함하여 워크플로의 중요한 모든 단계를 포함합니다.
 a| 
사전 요구 사항이 포함된 샘플 워크플로우 'Clustered Data ONTAP 스토리지에 VMware NFS 데이터 저장소 생성'에 대한 설명을 참조하십시오.



 a| 
워크플로가 생산 준비가 되어 있고 포털 페이지에 표시할 수 있는 경우에만 "생산 준비"를 "참"으로 설정합니다.
 a| 
없음



 a| 
기본적으로 ''예약된 요소 고려''를 true로 설정합니다. 실행 워크플로우를 미리 볼 때 WFA 플래너는 캐시 데이터베이스의 기존 개체와 함께 예약된 모든 개체를 고려합니다. 이 옵션이 "참"으로 설정된 경우 특정 워크플로를 계획할 때 다른 예약된 워크플로 또는 병렬로 실행되는 워크플로의 효과를 고려합니다
 a| 
* 시나리오 1
+
워크플로 1은 볼륨을 생성하며 1주일 후에 실행되도록 예약되어 있습니다. Workflow 2는 검색된 볼륨에 qtree 또는 LUN을 생성하며, 워크플로우 2가 하루 이내에 실행되는 경우 워크플로우 2에 대해 "'예약된 요소 고려''를 해제해야만 일주일 내에 생성되는 볼륨을 고려할 수 있습니다.

* 시나리오 2
+
워크플로 1은 '볼륨 만들기' 명령을 사용합니다. Aggregate에서 100GB 을 사용하는 예약된 워크플로 2가 있는 경우 계획 중에 워크플로 1은 워크플로 2에 대한 요구 사항을 고려해야 합니다.





 a| 
기본적으로 "요소 존재 유효성 검사 사용"은 "참"으로 설정됩니다
 a| 
* 시나리오 1
+
볼륨이 존재하는 경우에만 '볼륨 제거' 명령을 사용하여 먼저 이름별로 볼륨을 제거하는 워크플로우를 생성한 후 '볼륨 생성' 또는 '볼륨 클론'과 같은 다른 명령을 사용하여 볼륨을 다시 생성하는 경우 워크플로우에서 이 플래그를 사용해서는 안 됩니다. 볼륨 제거 효과는 볼륨 만들기 명령에 사용할 수 없게 되어 워크플로가 실패합니다.

* 시나리오 2
+
볼륨 만들기 명령은 특정 이름이 "vol198"인 워크플로에서 사용됩니다.

+
이 옵션이 true로 설정된 경우 WFA 플래너는 계획 중에 해당 이름의 볼륨이 지정된 어레이에 있는지 확인합니다. 볼륨이 있는 경우 계획 중에 워크플로가 실패합니다.





 a| 
워크플로에서 같은 명령을 두 번 이상 선택한 경우 명령 인스턴스에 적절한 표시 이름을 제공합니다.
 a| 
SnapVault로 LUN 생성, 매핑 및 보호 샘플 워크플로에서는 볼륨 생성 명령을 두 번 사용합니다. 그러나 이 표시 이름은 기본 볼륨 및 미러링된 대상 볼륨에 대해 "기본 볼륨 생성" 및 "보조 볼륨 생성"으로 적절하게 사용됩니다.

|===


== 사용자 입력

[cols="2*"]
|===
| 지침 | 예 


 a| 
이름:

* 이름을 ""$" 문자로 시작합니다.
* 각 단어의 시작 부분에 대문자를 사용합니다.
* 모든 용어와 약어에 대문자를 사용합니다.
* 밑줄을 사용하지 마십시오.

 a| 
'$Array'

'$VolumeName'



 a| 
표시 이름:

* 각 단어의 시작 부분에 대문자를 사용합니다.
* 단어를 공백으로 구분합니다.
* 입력에 특정 단위가 있는 경우 표시 이름에 대괄호로 단위를 직접 지정합니다.

 a| 
볼륨 이름

볼륨 크기(MB)



 a| 
설명:

* 각 사용자 입력에 대해 의미 있는 설명을 제공합니다.
* 필요한 경우 예를 제공합니다.
+
특히 사용자 입력이 특정 형식이어야 할 경우 이 작업을 수행해야 합니다.



사용자 입력 설명은 워크플로 실행 중 사용자 입력에 대한 도구 설명으로 표시됩니다.
 a| 
"iGroup"에 추가할 이니시에이터입니다. 예를 들어 이니시에이터의 IQN 또는 WWPN입니다.



 a| 
Type: 특정 값 집합으로 입력을 제한하려면 Enum 을 형식으로 선택합니다.
 a| 
프로토콜: iSCSI, FCP, 혼합



 a| 
유형: 사용자가 WFA 캐시에 있는 값 중에서 선택할 수 있는 경우 유형으로 Query를 선택합니다.
 a| 
$Array: 다음과 같은 쿼리가 있는 쿼리 유형:

[listing]
----
SELECT
	ip, name
FROM
	storage.array
----


 a| 
Type: 사용자 입력이 쿼리에서 가져온 값으로 제한되거나 지원되는 Enum 형식으로만 제한되어야 하는 경우 사용자 입력을 locked로 표시합니다.
 a| 
$Array: 잠긴 쿼리 유형: 캐시에 있는 배열만 선택할 수 있습니다.$Protocol: iSCSI, FCP, 혼합으로 유효한 값을 가진 잠긴 Enum 형식입니다. 유효한 값 이외의 값은 지원되지 않습니다.



 a| 
유형: 쿼리 유형 추가 열을 쿼리에 반환 값으로 추가하면 저장소 운영자가 사용자 입력을 올바르게 선택할 수 있습니다.
 a| 
$Aggregate: 이름, 총 크기 및 사용 가능한 크기를 제공하여 운영자가 애그리게이트를 선택하기 전에 속성을 알 수 있도록 합니다.



 a| 
유형: 사용자 입력에 대한 쿼리 TypeSQL 쿼리는 그 앞의 다른 사용자 입력을 참조할 수 있습니다. 어레이의 vFiler 유닛, 애그리게이트의 볼륨, SVM(스토리지 가상 머신)의 LUN 등 다른 사용자 입력을 기반으로 쿼리 결과를 제한하는 데 사용할 수 있습니다.
 a| 
샘플 워크플로우 'Create a clustered Data ONTAP Volume'에서 VserverName에 대한 쿼리는 다음과 같습니다.

[listing]
----
SELECT
    vserver.name
FROM
    cm_storage.cluster cluster,
    cm_storage.vserver vserver
WHERE
    vserver.cluster_id = cluster.id
    AND cluster.name = '${ClusterName}'
    AND vserver.type = 'cluster'
ORDER BY
    vserver.name ASC
----
이 쿼리는 $\{clusterName}을(를) 참조합니다. 여기서 $clusterName은 $VserverName 사용자 입력 앞의 사용자 입력 이름입니다.



 a| 
형식: Boolean 형식의 사용자 입력에 대해 값이 ""true, false""인 부울 형식을 사용합니다. 이렇게 하면 사용자 입력을 직접 사용하여 워크플로 디자인에 내부 식을 작성하는 데 도움이 됩니다. 예를 들어, $UserInputName==''Yes' 대신 $UserInputName을 사용할 수 있습니다.
 a| 
'$CreateCIFSShare': 유효한 값이 ""true"" 또는 ""false""인 부울 형식



 a| 
type: 문자열 및 숫자 형식의 경우 특정 형식으로 값의 유효성을 검사하려는 경우 값 열에 정규식을 사용합니다.

IP 주소 및 네트워크 마스크 입력에 정규식을 사용합니다.
 a| 
위치별 사용자 입력은 ""[A-Z][A-Z]\-0[1-9]"로 나타낼 수 있습니다. 이 사용자 입력에는 "'US-01'''''NB-02''''가 허용되지만 nb-00'은 사용할 수 없습니다.



 a| 
유형: 숫자 형식의 경우 값 열에 범위 기반 유효성 검사를 지정할 수 있습니다.
 a| 
생성할 LUN 수의 경우 값 열의 항목은 1~20입니다.



 a| 
그룹: 관련 사용자 입력을 적절한 버킷으로 그룹화하고 그룹 이름을 지정합니다.
 a| 
모든 스토리지 관련 사용자 입력에 대한 "스토리지 세부 정보". 모든 VMware 관련 사용자 입력에 대한 "Datastore Details"



 a| 
필수: 워크플로우를 실행하기 위해 사용자 입력 값이 필요한 경우 사용자 입력을 필수로 표시합니다. 이렇게 하면 사용자 입력 화면이 사용자의 입력을 받아 입력하게 됩니다.
 a| 
"Create NFS Volume" 워크플로우에서 ""$VolumeName".



 a| 
기본값: 사용자 입력에 대부분의 워크플로 실행에 사용할 수 있는 기본값이 있는 경우 값을 제공합니다. 이렇게 하면 기본값이 목적을 수행하는 경우 사용자가 실행 중에 더 적은 입력을 제공할 수 있습니다.
 a| 
없음

|===


== 상수, 변수 및 반환 매개 변수

|===


| 지침 | 예 


 a| 
상수: 여러 명령에 대한 매개 변수를 정의하기 위해 공통 값을 사용할 때 상수를 정의합니다.
 a| 
_aggregate_over오버커밋_threshold_의 경우 SnapVault 샘플 워크플로우를 사용하여 LUN을 생성, 매핑 및 보호합니다.



 a| 
상수:이름

* 각 단어의 시작 부분에 대문자를 사용합니다.
* 모든 용어와 약어에 대문자를 사용합니다.
* 밑줄을 사용하지 마십시오.
* 상수 이름의 모든 문자는 대문자를 사용합니다.

 a| 
_aggregate_used_space_threshold_입니다

_ActualVolumeSizeInMB _



 a| 
변수: 명령 매개 변수 상자 중 하나에 정의된 개체에 이름을 제공합니다. 변수는 자동으로 생성된 이름이며 변경할 수 있습니다.
 a| 
없음



 a| 
변수: 이름은 변수 이름에 소문자를 사용합니다.
 a| 
볼륨1

cifs_share 를 참조하십시오



 a| 
반환 매개 변수: 워크플로 계획 및 실행이 계획 중에 계산되거나 선택된 일부 값을 반환해야 할 때 반환 매개 변수를 사용합니다. 이 값은 웹 서비스에서 워크플로가 실행될 때 미리 보기 모드에서 사용할 수 있습니다.
 a| 
집계: 리소스 선택 논리를 사용하여 집계를 선택한 경우 실제 선택된 집계를 반환 매개 변수로 정의할 수 있습니다.

|===