---
permalink: workflows/task-test-the-wfa-reservation-script-for-commands.html 
sidebar: sidebar 
keywords: test, reservation, scripts, written, oncommand, workflow, automation, commands, playground, database, ensure, affect, table 
summary: 'WFA(OnCommand Workflow Automation) 명령에 대해 작성한 예약 스크립트를 운동장 데이터베이스에서 테스트하여 스크립트가 제대로 작동하고 WFA 데이터베이스 테이블에 영향을 미치지 않는지 확인할 수 있습니다.' 
---
= 명령에 대한 예약 스크립트를 테스트합니다
:allow-uri-read: 
:icons: font
:imagesdir: ../media/


[role="lead"]
WFA(OnCommand Workflow Automation) 명령에 대해 작성한 예약 스크립트를 운동장 데이터베이스에서 테스트하여 스크립트가 제대로 작동하고 WFA 데이터베이스 테이블에 영향을 미치지 않는지 확인할 수 있습니다.

기본 WFA 설치 경로가 이 절차에 사용됩니다. 설치 중에 기본 위치를 변경한 경우 변경된 WFA 설치 경로를 사용해야 합니다.

.단계
. WFA 서버에서 명령 프롬프트를 열고 디렉터리를 'c:\Program Files\NetApp\WFA\MySQL\bin'으로 변경합니다
. mysqldump -u WFA -pWfa123--single-transaction--skip-add-drop-table database_table > dump_location 명령을 사용하여 WFA 데이터베이스의 덤프를 생성합니다
+
CM_STORAGE 데이터베이스 테이블의 덤프를 생성하는 명령: mysqldump -u WFA -pWfa123--single-transaction--skip-add-drop -table cm_storage > c:\tmp\cmSt2.sql"

. mysql-u dWFA-pwfa123 fground <dump_location' 명령을 사용하여 생성한 덤프를 WFA 운동장 데이터베이스에 복원합니다
+
mysql -u WFA -pWfa123 놀이터 <c:\tmp\cmSt2.sql"

. WFA 명령을 생성 또는 편집하고 * Reservation * 탭에 예약 스크립트를 작성합니다.
+
예약 및 검증 스크립트에서 놀이터 데이터베이스만 사용하는지 확인해야 합니다.

. 워크플로를 만들거나 편집하고, 워크플로에 명령을 추가한 다음 워크플로를 실행합니다.
. 예약 및 검증 스크립트가 예상대로 작동하는지 확인합니다.
+
WFA 데이터 소스 수집 프로세스에서는 놀이터 데이터베이스가 업데이트되지 않습니다. 수동으로 명령에 의해 생성된 예약을 제거해야 합니다.


